"""Extra Trees candidate selection and the saved-model manifest."""

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import numpy as np
import pandas as pd
from joblib import load as load_joblib  # type: ignore[import-untyped]
from sklearn.ensemble import ExtraTreesRegressor  # type: ignore[import-untyped]

from src.config import RANDOM_STATE
from src.dataset import JoinedFeatureContract
from src.model_selection import select_candidate as _select_candidate
from src.model_selection import tie_breaking_policy as _tie_breaking_policy
from src.training import numeric_predictors, validate_predictions

# Manifest layout written by this module. There is no back-compatible reader:
# a manifest from an older schema must be regenerated by re-running the notebook.
MANIFEST_SCHEMA_VERSION = "1.0"
SEALED_TEST_METRIC_NAMES = ("test_mae", "test_rmse", "test_me", "test_r2")
MANIFEST_GUIDANCE = (
    "Run 04_06_train_extra_trees.ipynb through its sealed-test cell to write one."
)

type ExtraTreesMaxFeatures = Literal["sqrt"] | float
type ExtraTreesCandidateKey = tuple[str, int | None, int, int, ExtraTreesMaxFeatures]

_TIE_BREAK_DESCRIPTIONS = [
    "fewer features",
    "larger min_samples_leaf",
    "shallower bounded max_depth (unbounded max_depth last)",
    "fewer n_estimators",
    'max_features="sqrt" preferred, then 0.5, then 1.0',
    "stable subset name",
]
_CANDIDATE_PARAMETER_COLUMNS = {
    "subset",
    "feature_count",
    "max_depth",
    "n_estimators",
    "min_samples_leaf",
    "max_features",
}


def normalize_candidate_key(
    *,
    subset: object,
    max_depth: object,
    n_estimators: object,
    min_samples_leaf: object,
    max_features: object,
) -> ExtraTreesCandidateKey:
    """Normalize one sampled or MLflow-loaded Extra Trees candidate key.

    MLflow returns parameter values as strings, while ``ParameterSampler`` and
    pandas may represent the same values as Python, NumPy, or nullable scalars.
    This function is the single strict normalization boundary used by notebook
    orchestration, candidate selection, and manifest validation.

    Args:
        subset: Feature-subset name.
        max_depth: Positive integer depth or an unbounded-depth sentinel.
        n_estimators: Positive integer tree count.
        min_samples_leaf: Positive integer minimum leaf size.
        max_features: ``"sqrt"``, ``0.5``, or ``1.0``.

    Returns:
        A hashable candidate key with canonical Python scalar values.

    Raises:
        ValueError: If any candidate value is missing or outside the supported
            Extra Trees search space.
    """
    if not isinstance(subset, str) or not subset:
        raise ValueError("subset must be a non-empty string")
    return (
        subset,
        _coerce_max_depth(max_depth),
        _coerce_positive_int(n_estimators, name="n_estimators"),
        _coerce_positive_int(min_samples_leaf, name="min_samples_leaf"),
        _coerce_max_features(max_features),
    )


def select_candidate(
    cv_results: pd.DataFrame, metric: str = "rmse"
) -> tuple[str, int | None, int, int, ExtraTreesMaxFeatures]:
    """Select an Extra Trees candidate using deterministic simplicity rules.

    Candidates are ranked by the requested aggregate CV metric. Ties are
    resolved by fewer features, larger leaves, shallower bounded trees, fewer
    trees, the preferred ``max_features`` ordering, and finally subset name.

    Args:
        cv_results: One row per subset/hyperparameter candidate with aggregate
            CV metric columns named ``mae_mean`` and ``rmse_mean``.
        metric: Ranking metric, either ``"mae"`` or ``"rmse"``.

    Returns:
        The winning subset, maximum depth, estimator count, minimum leaf size,
        and maximum-feature setting.

    Raises:
        ValueError: If the metric is invalid, results are empty or incomplete,
            ranking values are null/non-finite, or a parameter is invalid.
    """
    ranked = _normalized_candidate_results(cv_results)
    metric_column = f"{metric}_mean"
    winner = _select_candidate(
        ranked,
        metric,
        tie_break_columns=[
            "feature_count",
            "__min_samples_leaf",
            "__max_depth",
            "n_estimators",
            "__max_features",
            "subset",
        ],
    )
    metric_values = pd.to_numeric(ranked[metric_column], errors="coerce")
    if not np.isfinite(metric_values.to_numpy(dtype=float)).all():
        raise ValueError("CV candidate results contain non-finite ranking values")
    return normalize_candidate_key(
        subset=winner["subset"],
        max_depth=winner["max_depth"],
        n_estimators=winner["n_estimators"],
        min_samples_leaf=winner["min_samples_leaf"],
        max_features=winner["max_features"],
    )


def tie_breaking_policy(selection_metric: str) -> list[str]:
    """Describe the candidate tie-breaking order used by ``select_candidate``.

    Args:
        selection_metric: Aggregate CV metric used to rank candidates.

    Returns:
        Ordered tie-breaking rules, including the primary metric.
    """
    return _tie_breaking_policy(selection_metric, _TIE_BREAK_DESCRIPTIONS)


def build_extra_trees_estimator(
    *,
    n_estimators: int,
    max_depth: int | None,
    min_samples_leaf: int,
    max_features: ExtraTreesMaxFeatures,
    bootstrap: bool,
    n_jobs: int = -1,
    random_state: int = RANDOM_STATE,
) -> ExtraTreesRegressor:
    """Build one native multi-output Extra Trees estimator.

    The same construction path is used for each validation fold and the final
    retrain. Extra Trees is tree based, so no predictor scaling is applied.

    Args:
        n_estimators: Number of trees in the forest.
        max_depth: Maximum tree depth, or ``None`` for unrestricted depth.
        min_samples_leaf: Minimum samples required at each leaf.
        max_features: Features considered at each split: ``"sqrt"`` or a
            fraction of the input features.
        bootstrap: Whether bootstrap samples are used when fitting trees.
        n_jobs: Number of parallel threads used by the estimator.
        random_state: Seed for reproducible tree sampling.

    Returns:
        A configured ``ExtraTreesRegressor`` supporting multi-output targets.

    Raises:
        TypeError: If ``bootstrap`` is not a boolean.
        ValueError: If a hyperparameter is outside the supported search space.
    """
    if n_estimators <= 0:
        raise ValueError("n_estimators must be positive")
    if max_depth is not None and max_depth <= 0:
        raise ValueError("max_depth must be positive or None")
    if min_samples_leaf <= 0:
        raise ValueError("min_samples_leaf must be positive")
    if not isinstance(bootstrap, bool):
        raise TypeError("bootstrap must be a boolean")
    max_features = _coerce_max_features(max_features)
    if max_features not in {"sqrt", 0.5, 1.0}:
        raise ValueError('max_features must be "sqrt", 0.5, or 1.0')
    return ExtraTreesRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        bootstrap=bootstrap,
        n_jobs=n_jobs,
        random_state=random_state,
    )


@dataclass(frozen=True)
class ExtraTreesManifest:
    """The durable record of one completed Extra Trees execution.

    Attributes:
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        station_id: Target station the model predicts.
        selected_subset: Name of the winning ablation subset.
        selected_max_depth: Winning maximum depth, or ``None`` if unbounded.
        selected_n_estimators: Winning number of trees.
        selected_min_samples_leaf: Winning minimum number of samples per leaf.
        selected_max_features: Winning feature-sampling setting per split.
        bootstrap: Notebook-wide bootstrap-sampling configuration.
        random_state: Seed used by every fold fit and the final retrain.
        selection_metric: Aggregate CV metric used to rank candidates.
        selected_feature_columns: Ordered predictors used to fit the model.
        target_columns: Ordered direct-forecast target columns.
        cv_results: One row per subset/hyperparameter candidate with CV metrics.
        sealed_test_metrics: Aggregate sealed-test MAE, RMSE, ME, and R².
        horizon_metrics: One sealed-test metric row per forecast horizon.
    """

    execution_uuid: str
    station_id: str
    selected_subset: str
    selected_max_depth: int | None
    selected_n_estimators: int
    selected_min_samples_leaf: int
    selected_max_features: ExtraTreesMaxFeatures
    bootstrap: bool
    random_state: int
    selection_metric: str
    selected_feature_columns: tuple[str, ...]
    target_columns: tuple[str, ...]
    cv_results: pd.DataFrame
    sealed_test_metrics: dict[str, float]
    horizon_metrics: pd.DataFrame


def save_extra_trees_manifest(
    path: Path,
    *,
    model_path: Path,
    execution_uuid: str,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
    selected_subset: str,
    selected_max_depth: int | None,
    selected_n_estimators: int,
    selected_min_samples_leaf: int,
    selected_max_features: ExtraTreesMaxFeatures,
    bootstrap: bool,
    selection_metric: str,
    cv_results: pd.DataFrame,
    sealed_test_metrics: Mapping[str, float],
    per_horizon_metrics: pd.DataFrame,
    cohort: Mapping[str, object],
    training: Mapping[str, object],
) -> None:
    """Write the manifest for a completed Extra Trees execution.

    Args:
        path: Manifest JSON path to write.
        model_path: Saved model joblib path.
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        contract: Joined-feature contract used for fitting.
        feature_subsets: Named ablation subsets in contract order.
        selected_subset: Winning subset name.
        selected_max_depth: Winning maximum tree depth.
        selected_n_estimators: Winning tree count.
        selected_min_samples_leaf: Winning minimum leaf size.
        selected_max_features: Winning split-feature setting.
        bootstrap: Whether bootstrap samples were used for every fit.
        selection_metric: Aggregate CV metric used for selection.
        cv_results: Candidate rows and aggregate CV metrics.
        sealed_test_metrics: Aggregate sealed-test metrics.
        per_horizon_metrics: Sealed-test metrics keyed by horizon.
        cohort: Common-cohort eligibility provenance.
        training: Training-artifact and time-range provenance.

    Raises:
        TypeError: If ``bootstrap`` is not a boolean.
        ValueError: If selected parameters/subsets, CV metrics, aggregate
            metrics, or horizon metrics are invalid.
    """
    if selected_subset not in feature_subsets:
        raise ValueError(f"Selected subset {selected_subset!r} is not a known subset")
    _validate_cv_parameters(cv_results)
    if selection_metric not in {"mae", "rmse"}:
        raise ValueError("CV selection metric must be either 'mae' or 'rmse'")
    _ = build_extra_trees_estimator(
        n_estimators=selected_n_estimators,
        max_depth=selected_max_depth,
        min_samples_leaf=selected_min_samples_leaf,
        max_features=selected_max_features,
        bootstrap=bootstrap,
    )
    missing_metrics = sorted(
        set(SEALED_TEST_METRIC_NAMES).difference(sealed_test_metrics)
    )
    if missing_metrics:
        raise ValueError(f"Sealed-test metrics are missing: {missing_metrics}")
    if not all(
        np.isfinite(float(sealed_test_metrics[name]))
        for name in SEALED_TEST_METRIC_NAMES
    ):
        raise ValueError("Sealed-test metrics contain non-finite values")
    horizon_records = _horizon_records(per_horizon_metrics, contract)

    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "model_path": str(model_path),
        "execution_uuid": execution_uuid,
        "model_type": "sklearn.ensemble.ExtraTreesRegressor",
        "estimator": "ExtraTreesRegressor",
        "preprocessor": "None (tree-based, no scaling)",
        "station_id": contract.station_id,
        "forecast_horizon_hours": len(contract.target_columns),
        "full_feature_columns": list(contract.predictor_columns),
        "selected_subset": selected_subset,
        "selected_feature_columns": list(feature_subsets[selected_subset]),
        "feature_subsets": {
            name: list(columns) for name, columns in feature_subsets.items()
        },
        "target_columns": list(contract.target_columns),
        "selected_max_depth": selected_max_depth,
        "selected_n_estimators": int(selected_n_estimators),
        "selected_min_samples_leaf": int(selected_min_samples_leaf),
        "selected_max_features": selected_max_features,
        "bootstrap": bootstrap,
        "random_state": RANDOM_STATE,
        "selection_metric": selection_metric,
        "tie_breaking": tie_breaking_policy(selection_metric),
        "cv_results": _cv_results_records(cv_results),
        "sealed_test_metrics": {
            name: float(sealed_test_metrics[name]) for name in SEALED_TEST_METRIC_NAMES
        },
        "horizon_metrics": horizon_records,
        "common_cohort_eligibility": dict(cohort),
        "training": dict(training),
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def load_extra_trees_manifest(
    path: Path,
    *,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
) -> ExtraTreesManifest:
    """Load an Extra Trees manifest and validate the current data contract.

    Args:
        path: Manifest JSON path to read.
        contract: Current joined-feature contract for the target station.
        feature_subsets: Named feature subsets built from ``contract``.

    Returns:
        A validated :class:`ExtraTreesManifest`.

    Raises:
        FileNotFoundError: If no manifest exists.
        TypeError: If the recorded bootstrap configuration is not boolean.
        ValueError: If schema, feature, target, subset, or metric contracts
            disagree with the current inputs.
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing Extra Trees model manifest: {path}. {MANIFEST_GUIDANCE}"
        )
    manifest = json.loads(path.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != MANIFEST_SCHEMA_VERSION:
        raise ValueError(
            f"Extra Trees manifest schema version {manifest.get('schema_version')!r} "
            f"is not {MANIFEST_SCHEMA_VERSION!r}. {MANIFEST_GUIDANCE}"
        )
    if manifest.get("station_id") != contract.station_id:
        raise ValueError(
            "Extra Trees manifest station_id does not match the current target station"
        )
    if manifest.get("forecast_horizon_hours") != len(contract.target_columns):
        raise ValueError(
            "Extra Trees manifest forecast horizon does not match the current contract"
        )
    if tuple(manifest.get("full_feature_columns", ())) != contract.predictor_columns:
        raise ValueError(
            "Extra Trees manifest full feature contract does not match the current contract"
        )
    if tuple(manifest.get("target_columns", ())) != contract.target_columns:
        raise ValueError(
            "Extra Trees manifest target contract does not match the current contract"
        )
    selected_subset = manifest.get("selected_subset")
    if selected_subset not in feature_subsets:
        raise ValueError(
            f"Extra Trees manifest selected subset {selected_subset!r} is not "
            "a subset of the current contract"
        )
    selected_feature_columns = tuple(manifest.get("selected_feature_columns", ()))
    if selected_feature_columns != tuple(feature_subsets[selected_subset]):
        raise ValueError(
            "Extra Trees manifest selected features do not match the selected subset contract"
        )
    cv_results = pd.DataFrame(manifest.get("cv_results", ()))
    _validate_cv_parameters(cv_results)
    bootstrap = manifest.get("bootstrap")
    if not isinstance(bootstrap, bool):
        raise TypeError("Extra Trees manifest bootstrap must be a boolean")
    if manifest.get("random_state") != RANDOM_STATE:
        raise ValueError(
            "Extra Trees manifest random_state does not match the configured random state"
        )
    selected_max_depth = _coerce_max_depth(manifest["selected_max_depth"])
    selected_n_estimators = int(manifest["selected_n_estimators"])
    selected_min_samples_leaf = int(manifest["selected_min_samples_leaf"])
    selected_max_features = _coerce_max_features(manifest["selected_max_features"])
    _ = build_extra_trees_estimator(
        n_estimators=selected_n_estimators,
        max_depth=selected_max_depth,
        min_samples_leaf=selected_min_samples_leaf,
        max_features=selected_max_features,
        bootstrap=bootstrap,
        random_state=RANDOM_STATE,
    )
    if manifest.get("selection_metric") not in {"mae", "rmse"}:
        raise ValueError("Extra Trees manifest selection metric is invalid")
    sealed_metrics = manifest.get("sealed_test_metrics", {})
    missing_metrics = sorted(set(SEALED_TEST_METRIC_NAMES).difference(sealed_metrics))
    if missing_metrics:
        raise ValueError(f"Sealed-test metrics are missing: {missing_metrics}")
    if not all(
        np.isfinite(float(sealed_metrics[name])) for name in SEALED_TEST_METRIC_NAMES
    ):
        raise ValueError("Sealed-test metrics contain non-finite values")
    raw_horizon_metrics = pd.DataFrame(manifest.get("horizon_metrics", ()))
    horizon_for_validation = raw_horizon_metrics.rename(
        columns={f"test_{metric}": metric for metric in ("mae", "rmse", "me", "r2")}
    )
    _horizon_records(horizon_for_validation, contract)
    return ExtraTreesManifest(
        execution_uuid=str(manifest["execution_uuid"]),
        station_id=str(manifest["station_id"]),
        selected_subset=str(selected_subset),
        selected_max_depth=selected_max_depth,
        selected_n_estimators=selected_n_estimators,
        selected_min_samples_leaf=selected_min_samples_leaf,
        selected_max_features=selected_max_features,
        bootstrap=bootstrap,
        random_state=int(manifest["random_state"]),
        selection_metric=str(manifest["selection_metric"]),
        selected_feature_columns=selected_feature_columns,
        target_columns=contract.target_columns,
        cv_results=cv_results,
        sealed_test_metrics={
            name: float(sealed_metrics[name]) for name in SEALED_TEST_METRIC_NAMES
        },
        horizon_metrics=raw_horizon_metrics,
    )


def score_saved_model(
    manifest: ExtraTreesManifest,
    model_path: Path,
    test_rows: pd.DataFrame,
) -> np.ndarray:
    """Reload a saved Extra Trees and score the sealed-test cohort.

    Args:
        manifest: Validated manifest describing the saved model.
        model_path: Saved model joblib path.
        test_rows: Eligible sealed-test rows to score.

    Returns:
        Validated predictions ordered like the manifest's targets.
    """
    model = load_joblib(model_path)
    return validate_predictions(
        model.predict(numeric_predictors(test_rows, manifest.selected_feature_columns)),
        expected_rows=len(test_rows),
        target_columns=list(manifest.target_columns),
        artifact_name="saved Extra Trees sealed-test",
    )


def _validate_cv_parameters(cv_results: pd.DataFrame) -> None:
    """Validate candidate columns and values before ranking or persistence."""
    normalized = _normalized_candidate_results(cv_results)
    missing = sorted({"mae_mean", "rmse_mean"}.difference(normalized.columns))
    if missing or normalized.empty:
        raise ValueError(f"CV results are empty or missing columns: {missing}")
    for column in normalized.columns:
        if column.endswith(("_mean", "_std")):
            numeric = pd.to_numeric(normalized[column], errors="coerce")
            if not np.isfinite(numeric.to_numpy(dtype=float)).all():
                raise ValueError("CV candidate results contain non-finite values")


def _normalized_candidate_results(cv_results: pd.DataFrame) -> pd.DataFrame:
    """Return candidate parameters with canonical values and ranking keys."""
    missing = sorted(_CANDIDATE_PARAMETER_COLUMNS.difference(cv_results.columns))
    if missing:
        raise ValueError(f"CV results are empty or missing columns: {missing}")

    normalized = cv_results.copy()
    keys = [
        normalize_candidate_key(
            subset=row.subset,
            max_depth=row.max_depth,
            n_estimators=row.n_estimators,
            min_samples_leaf=row.min_samples_leaf,
            max_features=row.max_features,
        )
        for row in normalized.itertuples()
    ]
    normalized["subset"] = [key[0] for key in keys]
    normalized["max_depth"] = [key[1] for key in keys]
    normalized["n_estimators"] = [key[2] for key in keys]
    normalized["min_samples_leaf"] = [key[3] for key in keys]
    normalized["max_features"] = [key[4] for key in keys]
    normalized["feature_count"] = [
        _coerce_positive_int(value, name="feature_count")
        for value in normalized["feature_count"]
    ]
    normalized["__min_samples_leaf"] = -normalized["min_samples_leaf"]
    normalized["__max_depth"] = normalized["max_depth"].map(_max_depth_sort_key)
    normalized["__max_features"] = normalized["max_features"].map(
        _max_features_sort_key
    )
    return normalized


def _coerce_positive_int(value: object, *, name: str) -> int:
    """Coerce one positive integer parameter from Python or MLflow values."""
    try:
        numeric = float(str(value))
    except (TypeError, ValueError) as error:
        raise ValueError(f"{name} must be a positive integer") from error
    integer = int(numeric) if np.isfinite(numeric) else 0
    if integer <= 0 or numeric != integer:
        raise ValueError(f"{name} must be a positive integer")
    return integer


def _coerce_max_depth(value: object) -> int | None:
    """Coerce a nullable depth value from pandas/JSON to a Python scalar."""
    if value is None or value is pd.NA:
        return None
    text = str(value).strip()
    if text.lower() in {"", "none", "nan"}:
        return None
    try:
        numeric = float(text)
    except ValueError as error:
        raise ValueError("max_depth must be a positive integer or None") from error
    if not np.isfinite(numeric):
        raise ValueError("max_depth must be a positive integer or None")
    depth = int(numeric)
    if depth <= 0 or numeric != depth:
        raise ValueError("max_depth must be a positive integer or None")
    return depth


def _max_depth_sort_key(value: object) -> float:
    depth = _coerce_max_depth(value)
    return float(depth) if depth is not None else float("inf")


def _coerce_max_features(value: object) -> ExtraTreesMaxFeatures:
    """Coerce and validate the supported ``max_features`` values."""
    if isinstance(value, str) and value == "sqrt":
        return "sqrt"
    try:
        numeric = float(str(value))
    except (TypeError, ValueError) as error:
        raise ValueError('max_features must be "sqrt", 0.5, or 1.0') from error
    if not np.isfinite(numeric) or numeric not in {0.5, 1.0}:
        raise ValueError('max_features must be "sqrt", 0.5, or 1.0')
    return numeric


def _max_features_sort_key(value: object) -> float:
    value = _coerce_max_features(value)
    return {"sqrt": 0.0, 0.5: 1.0, 1.0: 2.0}[value]


def _cv_results_records(cv_results: pd.DataFrame) -> list[dict[str, object]]:
    """Convert candidate results to JSON-safe records."""
    records: list[dict[str, object]] = []
    int_columns = {"feature_count", "n_estimators", "min_samples_leaf"}
    for row in cv_results.to_dict(orient="records"):
        record: dict[str, object] = {}
        for key, value in row.items():
            if key == "subset":
                record[str(key)] = str(value)
            elif key == "max_depth":
                record[str(key)] = _coerce_max_depth(value)
            elif key == "max_features":
                record[str(key)] = _coerce_max_features(value)
            elif key in int_columns:
                record[str(key)] = int(value)
            else:
                record[str(key)] = float(value)
        records.append(record)
    return records


def _horizon_records(
    per_horizon_metrics: pd.DataFrame,
    contract: JoinedFeatureContract,
) -> list[dict[str, object]]:
    """Convert per-horizon metrics to JSON-safe, contract-ordered records."""
    expected_horizons = list(range(1, len(contract.target_columns) + 1))
    missing_columns = sorted(
        {"horizon_hours", "mae", "rmse", "me", "r2"}.difference(
            per_horizon_metrics.columns
        )
    )
    if missing_columns:
        raise ValueError(
            f"Sealed-test horizon metrics are missing columns: {missing_columns}"
        )
    if per_horizon_metrics["horizon_hours"].tolist() != expected_horizons:
        raise ValueError(
            "Sealed-test horizon metrics do not match the forecast contract"
        )
    records: list[dict[str, object]] = []
    for horizon, row in zip(
        expected_horizons, per_horizon_metrics.itertuples(), strict=True
    ):
        values = {
            f"test_{metric}": float(getattr(row, metric))
            for metric in ("mae", "rmse", "me", "r2")
        }
        if not all(np.isfinite(value) for value in values.values()):
            raise ValueError("Sealed-test horizon metrics contain non-finite values")
        records.append({"horizon_hours": horizon, **values})
    return records
