"""MLP candidate selection and the saved-model manifest that records it."""

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from joblib import load as load_joblib  # type: ignore[import-untyped]
from sklearn.compose import (  # type: ignore[import-untyped]
    ColumnTransformer,
    TransformedTargetRegressor,
)
from sklearn.neural_network import MLPRegressor  # type: ignore[import-untyped]
from sklearn.pipeline import Pipeline  # type: ignore[import-untyped]
from sklearn.preprocessing import StandardScaler  # type: ignore[import-untyped]

from src.config import RANDOM_STATE
from src.dataset import JoinedFeatureContract
from src.model_selection import select_candidate as _select_candidate
from src.model_selection import tie_breaking_policy as _tie_breaking_policy
from src.training import numeric_predictors, validate_predictions

# Manifest layout written by this module. There is no back-compatible reader:
# a manifest from an older schema must be regenerated by re-running the notebook.
MANIFEST_SCHEMA_VERSION = "1.0"
# Aggregate sealed-test metrics every manifest must carry.
SEALED_TEST_METRIC_NAMES = ("test_mae", "test_rmse", "test_me", "test_r2")
MANIFEST_GUIDANCE = (
    "Run 04_03_train_mlp.ipynb through its sealed-test cell to write one."
)

_TIE_BREAK_COLUMNS = ["feature_count", "alpha", "hidden_layer_sizes", "subset"]
_TIE_BREAK_DESCRIPTIONS = [
    "fewer features",
    "smaller alpha",
    "smaller architecture string",
    "stable subset name",
]


def format_hidden_layer_sizes(hidden_layer_sizes: Sequence[int]) -> str:
    """Format a hidden-layer-sizes tuple as a stable, JSON-roundtrippable string.

    Args:
        hidden_layer_sizes: Ordered hidden layer widths, e.g. ``(64, 32)``.

    Returns:
        The layer widths joined by ``"x"``, e.g. ``"64x32"``.
    """
    return "x".join(str(int(size)) for size in hidden_layer_sizes)


def parse_hidden_layer_sizes(text: str) -> tuple[int, ...]:
    """Parse a hidden-layer-sizes string back into a tuple of ints.

    Args:
        text: A string produced by :func:`format_hidden_layer_sizes`, e.g. ``"64x32"``.

    Returns:
        The hidden layer widths, e.g. ``(64, 32)``.
    """
    return tuple(int(size) for size in text.split("x"))


def select_candidate(
    cv_results: pd.DataFrame, metric: str = "rmse"
) -> tuple[str, tuple[int, ...], float]:
    """Select one subset/hidden_layer_sizes/alpha triple with deterministic tie-breaking.

    Args:
        cv_results: One row per candidate subset/hidden_layer_sizes/alpha with
            mean CV metrics. ``hidden_layer_sizes`` is stored as a string (see
            :func:`format_hidden_layer_sizes`).
        metric: Ranking metric, either ``"mae"`` or ``"rmse"``.

    Returns:
        The winning candidate's subset name, hidden layer sizes, and alpha.

    Raises:
        ValueError: If the metric is invalid, results are empty or missing
            required columns, or ranking values contain nulls.
    """
    winner = _select_candidate(cv_results, metric, tie_break_columns=_TIE_BREAK_COLUMNS)
    return (
        str(winner["subset"]),
        parse_hidden_layer_sizes(str(winner["hidden_layer_sizes"])),
        float(winner["alpha"]),
    )


def tie_breaking_policy(selection_metric: str) -> list[str]:
    """Describe the candidate tie-breaking order :func:`select_candidate` applies.

    Args:
        selection_metric: Aggregate CV metric used to rank candidates.

    Returns:
        The ordered tie-breaking rules, recorded in the saved manifest.
    """
    return _tie_breaking_policy(selection_metric, _TIE_BREAK_DESCRIPTIONS)


def build_mlp_estimator(
    feature_columns: Sequence[str],
    *,
    hidden_layer_sizes: tuple[int, ...],
    alpha: float,
    activation: str = "relu",
    solver: str = "adam",
    learning_rate_init: float = 0.001,
    max_iter: int = 300,
    batch_size: int | str = "auto",
    early_stopping: bool = False,
    random_state: int = RANDOM_STATE,
) -> TransformedTargetRegressor:
    """Build one MLP estimator, with scaled predictors and a scaled target.

    The single construction path shared by the CV fold loop and the final
    retrain, so the saved model never diverges from what was cross-validated.
    Unlike Ridge's closed-form solve, ``MLPRegressor``'s gradient-based
    training needs a zero-centered, unit-scale target to converge, so target
    scaling is unconditional here (no log1p axis).

    Args:
        feature_columns: Ordered predictor columns the estimator is fitted on.
        hidden_layer_sizes: Ordered hidden layer widths.
        alpha: L2 regularization strength.
        activation: Hidden-layer activation function.
        solver: Weight-optimization solver.
        learning_rate_init: Initial learning rate (used by ``sgd``/``adam``).
        max_iter: Maximum number of training iterations.
        batch_size: Minibatch size for stochastic optimizers.
        early_stopping: Whether to stop training early on a validation split.
        random_state: Seed for weight initialization and the solver's
            stochastic optimization path.

    Returns:
        A ``TransformedTargetRegressor`` wrapping a ``StandardScaler`` +
        ``MLPRegressor`` pipeline, so ``.predict()`` always returns raw-scale
        values.
    """
    feature_columns = list(feature_columns)
    preprocessor = ColumnTransformer([("scale", StandardScaler(), feature_columns)])
    model = Pipeline(
        [
            ("preprocess", preprocessor),
            (
                "mlp",
                MLPRegressor(
                    hidden_layer_sizes=hidden_layer_sizes,
                    alpha=alpha,
                    activation=activation,
                    solver=solver,
                    learning_rate_init=learning_rate_init,
                    max_iter=max_iter,
                    batch_size=batch_size,
                    early_stopping=early_stopping,
                    random_state=random_state,
                ),
            ),
        ]
    )
    return TransformedTargetRegressor(regressor=model, transformer=StandardScaler())


@dataclass(frozen=True)
class MlpManifest:
    """The durable record of one completed MLP execution.

    Attributes:
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        station_id: Target station the model predicts.
        selected_subset: Name of the winning ablation subset.
        selected_hidden_layer_sizes: Winning hidden layer widths.
        selected_alpha: Winning L2 regularization strength.
        selection_metric: Aggregate CV metric used to rank candidates.
        selected_feature_columns: Ordered predictors the model was fitted on.
        target_columns: Ordered direct-forecast target columns.
        cv_results: One row per candidate subset/hidden_layer_sizes/alpha with
            its CV metrics.
        sealed_test_metrics: Aggregate sealed-test MAE, RMSE, ME, and R².
        horizon_metrics: One sealed-test metric row per forecast horizon.
    """

    execution_uuid: str
    station_id: str
    selected_subset: str
    selected_hidden_layer_sizes: tuple[int, ...]
    selected_alpha: float
    selection_metric: str
    selected_feature_columns: tuple[str, ...]
    target_columns: tuple[str, ...]
    cv_results: pd.DataFrame
    sealed_test_metrics: dict[str, float]
    horizon_metrics: pd.DataFrame


def save_mlp_manifest(
    path: Path,
    *,
    model_path: Path,
    execution_uuid: str,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
    selected_subset: str,
    selected_hidden_layer_sizes: tuple[int, ...],
    selected_alpha: float,
    selection_metric: str,
    cv_results: pd.DataFrame,
    sealed_test_metrics: Mapping[str, float],
    per_horizon_metrics: pd.DataFrame,
    cohort: Mapping[str, object],
    training: Mapping[str, object],
) -> None:
    """Write the manifest that records one completed MLP execution.

    Called once, after the sealed test has been scored, so the manifest never
    describes a run that did not finish.

    Args:
        path: Manifest JSON path to write.
        model_path: Saved MLP joblib model path.
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        contract: Joined-feature contract the model was fitted against.
        feature_subsets: The named ablation subsets, in contract order.
        selected_subset: Name of the winning ablation subset.
        selected_hidden_layer_sizes: Winning hidden layer widths.
        selected_alpha: Winning L2 regularization strength.
        selection_metric: Aggregate CV metric used to rank candidates.
        cv_results: One row per candidate subset/hidden_layer_sizes/alpha with
            its CV metrics.
        sealed_test_metrics: Aggregate sealed-test MAE, RMSE, ME, and R².
        per_horizon_metrics: Sealed-test metric rows keyed by horizon, as
            returned by :func:`src.metrics.metric_tables`.
        cohort: Common-cohort eligibility provenance.
        training: Training-artifact and time-range provenance.

    Raises:
        ValueError: If the selected subset is unknown, an aggregate sealed-test
            metric is missing or non-finite, or the per-horizon metrics do not
            cover the forecast contract exactly once.
    """
    if selected_subset not in feature_subsets:
        raise ValueError(f"Selected subset {selected_subset!r} is not a known subset")
    missing_metrics = sorted(
        set(SEALED_TEST_METRIC_NAMES).difference(sealed_test_metrics)
    )
    if missing_metrics:
        raise ValueError(f"Sealed-test metrics are missing: {missing_metrics}")
    if not all(
        np.isfinite(float(sealed_test_metrics[name]))
        for name in SEALED_TEST_METRIC_NAMES
    ):
        raise ValueError("Sealed-test metrics contain non-finite values")
    horizon_records = _horizon_records(per_horizon_metrics, contract)

    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "model_path": str(model_path),
        "execution_uuid": execution_uuid,
        "model_type": "sklearn.compose.TransformedTargetRegressor",
        "estimator": "MLPRegressor",
        "preprocessor": "StandardScaler (predictors), StandardScaler (target)",
        "station_id": contract.station_id,
        "forecast_horizon_hours": len(contract.target_columns),
        "full_feature_columns": list(contract.predictor_columns),
        "selected_subset": selected_subset,
        "selected_feature_columns": list(feature_subsets[selected_subset]),
        "feature_subsets": {
            name: list(columns) for name, columns in feature_subsets.items()
        },
        "target_columns": list(contract.target_columns),
        "selected_hidden_layer_sizes": list(selected_hidden_layer_sizes),
        "selected_alpha": float(selected_alpha),
        "selection_metric": selection_metric,
        "tie_breaking": tie_breaking_policy(selection_metric),
        "cv_results": _cv_results_records(cv_results),
        "sealed_test_metrics": {
            name: float(sealed_test_metrics[name]) for name in SEALED_TEST_METRIC_NAMES
        },
        "horizon_metrics": horizon_records,
        "common_cohort_eligibility": dict(cohort),
        "training": dict(training),
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def load_mlp_manifest(
    path: Path,
    *,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
) -> MlpManifest:
    """Load an MLP manifest and check it against the current contract.

    Args:
        path: Manifest JSON path to read.
        contract: Current joined-feature contract for the target station.
        feature_subsets: Named feature subsets built from ``contract``.

    Returns:
        The validated manifest.

    Raises:
        FileNotFoundError: If no manifest exists.
        ValueError: If the manifest was written by another schema version, or
            disagrees with the current contract or subset definitions.
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing MLP model manifest: {path}. {MANIFEST_GUIDANCE}"
        )
    manifest = json.loads(path.read_text(encoding="utf-8"))
    schema_version = manifest.get("schema_version")
    if schema_version != MANIFEST_SCHEMA_VERSION:
        raise ValueError(
            f"MLP manifest schema version {schema_version!r} is not "
            f"{MANIFEST_SCHEMA_VERSION!r}. {MANIFEST_GUIDANCE}"
        )
    if manifest.get("station_id") != contract.station_id:
        raise ValueError(
            "MLP manifest station_id does not match the current target station"
        )
    if manifest.get("forecast_horizon_hours") != len(contract.target_columns):
        raise ValueError(
            "MLP manifest forecast horizon does not match the current contract"
        )
    if tuple(manifest.get("full_feature_columns", ())) != contract.predictor_columns:
        raise ValueError(
            "MLP manifest full feature contract does not match the current contract"
        )
    if tuple(manifest.get("target_columns", ())) != contract.target_columns:
        raise ValueError(
            "MLP manifest target contract does not match the current contract"
        )
    selected_subset = manifest.get("selected_subset")
    if selected_subset not in feature_subsets:
        raise ValueError(
            f"MLP manifest selected subset {selected_subset!r} is not a subset of "
            "the current contract"
        )
    selected_feature_columns = tuple(manifest.get("selected_feature_columns", ()))
    if selected_feature_columns != tuple(feature_subsets[selected_subset]):
        raise ValueError(
            "MLP manifest selected features do not match the selected subset contract"
        )
    return MlpManifest(
        execution_uuid=str(manifest["execution_uuid"]),
        station_id=str(manifest["station_id"]),
        selected_subset=str(selected_subset),
        selected_hidden_layer_sizes=tuple(manifest["selected_hidden_layer_sizes"]),
        selected_alpha=float(manifest["selected_alpha"]),
        selection_metric=str(manifest["selection_metric"]),
        selected_feature_columns=selected_feature_columns,
        target_columns=contract.target_columns,
        cv_results=pd.DataFrame(manifest["cv_results"]),
        sealed_test_metrics={
            name: float(manifest["sealed_test_metrics"][name])
            for name in SEALED_TEST_METRIC_NAMES
        },
        horizon_metrics=pd.DataFrame(manifest["horizon_metrics"]),
    )


def score_saved_model(
    manifest: MlpManifest,
    model_path: Path,
    test_rows: pd.DataFrame,
) -> np.ndarray:
    """Reload the saved MLP model and score the sealed-test cohort.

    Args:
        manifest: Validated manifest describing the saved model.
        model_path: Saved MLP joblib model path.
        test_rows: Eligible sealed-test rows to score.

    Returns:
        Validated sealed-test predictions ordered like the manifest's targets.

    Raises:
        ValueError: If the reloaded model's predictions do not match the
            forecast contract.
    """
    model = load_joblib(model_path)
    return validate_predictions(
        model.predict(numeric_predictors(test_rows, manifest.selected_feature_columns)),
        expected_rows=len(test_rows),
        target_columns=list(manifest.target_columns),
        artifact_name="saved MLP sealed-test",
    )


def _cv_results_records(cv_results: pd.DataFrame) -> list[dict[str, object]]:
    """Convert the candidate table to JSON-safe records.

    Args:
        cv_results: One row per candidate subset/hidden_layer_sizes/alpha with
            its CV metrics.

    Returns:
        One record per candidate, with plain string, int, and float values.
    """
    return [
        {
            str(key): (
                str(value)
                if key in ("subset", "hidden_layer_sizes")
                else int(value)
                if key == "feature_count"
                else float(value)
            )
            for key, value in record.items()
        }
        for record in cv_results.to_dict(orient="records")
    ]


def _horizon_records(
    per_horizon_metrics: pd.DataFrame,
    contract: JoinedFeatureContract,
) -> list[dict[str, object]]:
    """Convert per-horizon sealed-test metrics to JSON-safe records.

    Args:
        per_horizon_metrics: Sealed-test metric rows keyed by horizon.
        contract: Joined-feature contract defining the expected horizons.

    Returns:
        One ``test_``-prefixed metric record per forecast horizon, in order.

    Raises:
        ValueError: If the horizons do not cover the forecast contract exactly
            once, or a metric is missing or non-finite.
    """
    expected_horizons = list(range(1, len(contract.target_columns) + 1))
    missing_columns = sorted(
        {"horizon_hours", "mae", "rmse", "me", "r2"}.difference(
            per_horizon_metrics.columns
        )
    )
    if missing_columns:
        raise ValueError(
            f"Sealed-test horizon metrics are missing columns: {missing_columns}"
        )
    if per_horizon_metrics["horizon_hours"].tolist() != expected_horizons:
        raise ValueError(
            "Sealed-test horizon metrics do not match the forecast contract"
        )
    records: list[dict[str, object]] = []
    for horizon, row in zip(
        expected_horizons, per_horizon_metrics.itertuples(), strict=True
    ):
        values = {
            f"test_{metric}": float(getattr(row, metric))
            for metric in ("mae", "rmse", "me", "r2")
        }
        if not all(np.isfinite(value) for value in values.values()):
            raise ValueError("Sealed-test horizon metrics contain non-finite values")
        records.append({"horizon_hours": horizon, **values})
    return records
