"""MLP candidate selection, construction, and model manifest helpers."""

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from joblib import load as load_joblib  # type: ignore[import-untyped]
from sklearn.compose import (  # type: ignore[import-untyped]
    ColumnTransformer,
    TransformedTargetRegressor,
)
from sklearn.neural_network import MLPRegressor  # type: ignore[import-untyped]
from sklearn.pipeline import Pipeline  # type: ignore[import-untyped]
from sklearn.preprocessing import StandardScaler  # type: ignore[import-untyped]

from src.config import RANDOM_STATE
from src.dataset import JoinedFeatureContract
from src.model_selection import select_candidate as _select_candidate
from src.model_selection import tie_breaking_policy as _tie_breaking_policy
from src.training import numeric_predictors, validate_predictions

# Manifest layout written by this module. There is no back-compatible reader:
# a manifest from an older schema must be regenerated by re-running the notebook.
MANIFEST_SCHEMA_VERSION = "3.0"
MANIFEST_GUIDANCE = (
    "Run 04_03_train_mlp.ipynb through its sealed-test cell to write one."
)

_TIE_BREAK_COLUMNS = ["feature_count", "alpha", "hidden_layer_sizes", "subset"]
_TIE_BREAK_DESCRIPTIONS = [
    "fewer features",
    "smaller alpha",
    "smaller architecture string",
    "stable subset name",
]


def format_hidden_layer_sizes(hidden_layer_sizes: Sequence[int]) -> str:
    """Format a hidden-layer-sizes tuple as a stable, JSON-roundtrippable string.

    Args:
        hidden_layer_sizes: Ordered hidden layer widths, e.g. ``(64, 32)``.

    Returns:
        The layer widths joined by ``"x"``, e.g. ``"64x32"``.
    """
    return "x".join(str(int(size)) for size in hidden_layer_sizes)


def parse_hidden_layer_sizes(text: str) -> tuple[int, ...]:
    """Parse a hidden-layer-sizes string back into a tuple of ints.

    Args:
        text: A string produced by :func:`format_hidden_layer_sizes`, e.g. ``"64x32"``.

    Returns:
        The hidden layer widths, e.g. ``(64, 32)``.
    """
    return tuple(int(size) for size in text.split("x"))


def select_candidate(
    cv_results: pd.DataFrame, metric: str = "rmse"
) -> tuple[str, tuple[int, ...], float]:
    """Select one subset/hidden_layer_sizes/alpha triple with deterministic tie-breaking.

    Args:
        cv_results: One row per candidate subset/hidden_layer_sizes/alpha with
            mean CV metrics. ``hidden_layer_sizes`` is stored as a string (see
            :func:`format_hidden_layer_sizes`).
        metric: Ranking metric, either ``"mae"`` or ``"rmse"``.

    Returns:
        The winning candidate's subset name, hidden layer sizes, and alpha.

    Raises:
        ValueError: If the metric is invalid, results are empty or missing
            required columns, or ranking values contain nulls.
    """
    winner = _select_candidate(cv_results, metric, tie_break_columns=_TIE_BREAK_COLUMNS)
    return (
        str(winner["subset"]),
        parse_hidden_layer_sizes(str(winner["hidden_layer_sizes"])),
        float(winner["alpha"]),
    )


def tie_breaking_policy(selection_metric: str) -> list[str]:
    """Describe the candidate tie-breaking order :func:`select_candidate` applies.

    Args:
        selection_metric: Aggregate CV metric used to rank candidates.

    Returns:
        The ordered tie-breaking rules.
    """
    return _tie_breaking_policy(selection_metric, _TIE_BREAK_DESCRIPTIONS)


def build_mlp_estimator(
    feature_columns: Sequence[str],
    *,
    hidden_layer_sizes: tuple[int, ...],
    alpha: float,
    activation: str = "relu",
    solver: str = "adam",
    learning_rate_init: float = 0.001,
    max_iter: int = 300,
    batch_size: int | str = "auto",
    early_stopping: bool = False,
    random_state: int = RANDOM_STATE,
) -> TransformedTargetRegressor:
    """Build one MLP estimator, with scaled predictors and a scaled target.

    The single construction path shared by the CV fold loop and the final
    retrain, so the saved model never diverges from what was cross-validated.
    Unlike Ridge's closed-form solve, ``MLPRegressor``'s gradient-based
    training needs a zero-centered, unit-scale target to converge, so target
    scaling is unconditional here (no log1p axis).

    Args:
        feature_columns: Ordered predictor columns the estimator is fitted on.
        hidden_layer_sizes: Ordered hidden layer widths.
        alpha: L2 regularization strength.
        activation: Hidden-layer activation function.
        solver: Weight-optimization solver.
        learning_rate_init: Initial learning rate (used by ``sgd``/``adam``).
        max_iter: Maximum number of training iterations.
        batch_size: Minibatch size for stochastic optimizers.
        early_stopping: Whether to stop training early on a validation split.
        random_state: Seed for weight initialization and the solver's
            stochastic optimization path.

    Returns:
        A ``TransformedTargetRegressor`` wrapping a ``StandardScaler`` +
        ``MLPRegressor`` pipeline, so ``.predict()`` always returns raw-scale
        values.
    """
    feature_columns = list(feature_columns)
    preprocessor = ColumnTransformer([("scale", StandardScaler(), feature_columns)])
    model = Pipeline(
        [
            ("preprocess", preprocessor),
            (
                "mlp",
                MLPRegressor(
                    hidden_layer_sizes=hidden_layer_sizes,
                    alpha=alpha,
                    activation=activation,
                    solver=solver,
                    learning_rate_init=learning_rate_init,
                    max_iter=max_iter,
                    batch_size=batch_size,
                    early_stopping=early_stopping,
                    random_state=random_state,
                ),
            ),
        ]
    )
    return TransformedTargetRegressor(regressor=model, transformer=StandardScaler())


@dataclass(frozen=True)
class MlpManifest:
    """The durable record of one completed MLP execution.

    Attributes:
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        station_id: Target station the model predicts.
        selected_subset: Name of the winning ablation subset.
        selected_hidden_layer_sizes: Winning hidden layer widths.
        selected_alpha: Winning L2 regularization strength.
        selected_feature_columns: Ordered predictors the model was fitted on.
        target_columns: Ordered direct-forecast target columns.
    """

    execution_uuid: str
    station_id: str
    selected_subset: str
    selected_hidden_layer_sizes: tuple[int, ...]
    selected_alpha: float
    selected_feature_columns: tuple[str, ...]
    target_columns: tuple[str, ...]


def save_mlp_manifest(
    path: Path,
    *,
    model_path: Path,
    execution_uuid: str,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
    selected_subset: str,
    selected_hidden_layer_sizes: tuple[int, ...],
    selected_alpha: float,
) -> None:
    """Write the model-only manifest for one fitted MLP estimator.

    Args:
        path: Manifest JSON path to write.
        model_path: Saved MLP joblib model path.
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        contract: Joined-feature contract the model was fitted against.
        feature_subsets: The named ablation subsets, in contract order.
        selected_subset: Name of the winning ablation subset.
        selected_hidden_layer_sizes: Winning hidden layer widths.
        selected_alpha: Winning L2 regularization strength.

    Raises:
        ValueError: If the selected subset is unknown.
    """
    if selected_subset not in feature_subsets:
        raise ValueError(f"Selected subset {selected_subset!r} is not a known subset")
    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "model_path": str(model_path),
        "execution_uuid": execution_uuid,
        "model_type": "sklearn.compose.TransformedTargetRegressor",
        "estimator": "MLPRegressor",
        "preprocessor": "StandardScaler (predictors), StandardScaler (target)",
        "station_id": contract.station_id,
        "forecast_horizon_hours": len(contract.target_columns),
        "selected_subset": selected_subset,
        "selected_feature_columns": list(feature_subsets[selected_subset]),
        "target_columns": list(contract.target_columns),
        "selected_hidden_layer_sizes": list(selected_hidden_layer_sizes),
        "selected_alpha": float(selected_alpha),
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def load_mlp_manifest(
    path: Path,
    *,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
) -> MlpManifest:
    """Load an MLP manifest and check it against the current contract.

    Args:
        path: Manifest JSON path to read.
        contract: Current joined-feature contract for the target station.
        feature_subsets: Named feature subsets built from ``contract``.

    Returns:
        The validated manifest.

    Raises:
        FileNotFoundError: If no manifest exists.
        ValueError: If the manifest was written by another schema version, or
            disagrees with the current contract or subset definitions.
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing MLP model manifest: {path}. {MANIFEST_GUIDANCE}"
        )
    manifest = json.loads(path.read_text(encoding="utf-8"))
    schema_version = manifest.get("schema_version")
    if schema_version != MANIFEST_SCHEMA_VERSION:
        raise ValueError(
            f"MLP manifest schema version {schema_version!r} is not "
            f"{MANIFEST_SCHEMA_VERSION!r}. {MANIFEST_GUIDANCE}"
        )
    if manifest.get("station_id") != contract.station_id:
        raise ValueError(
            "MLP manifest station_id does not match the current target station"
        )
    if manifest.get("forecast_horizon_hours") != len(contract.target_columns):
        raise ValueError(
            "MLP manifest forecast horizon does not match the current contract"
        )
    if tuple(manifest.get("target_columns", ())) != contract.target_columns:
        raise ValueError(
            "MLP manifest target contract does not match the current contract"
        )
    selected_subset = manifest.get("selected_subset")
    if selected_subset not in feature_subsets:
        raise ValueError(
            f"MLP manifest selected subset {selected_subset!r} is not a subset of "
            "the current contract"
        )
    selected_feature_columns = tuple(manifest.get("selected_feature_columns", ()))
    if selected_feature_columns != tuple(feature_subsets[selected_subset]):
        raise ValueError(
            "MLP manifest selected features do not match the selected subset contract"
        )
    return MlpManifest(
        execution_uuid=str(manifest["execution_uuid"]),
        station_id=str(manifest["station_id"]),
        selected_subset=str(selected_subset),
        selected_hidden_layer_sizes=tuple(manifest["selected_hidden_layer_sizes"]),
        selected_alpha=float(manifest["selected_alpha"]),
        selected_feature_columns=selected_feature_columns,
        target_columns=contract.target_columns,
    )


def score_saved_model(
    manifest: MlpManifest,
    model_path: Path,
    test_rows: pd.DataFrame,
) -> np.ndarray:
    """Reload the saved MLP model and score the sealed-test cohort.

    Args:
        manifest: Validated manifest describing the saved model.
        model_path: Saved MLP joblib model path.
        test_rows: Eligible sealed-test rows to score.

    Returns:
        Validated sealed-test predictions ordered like the manifest's targets.

    Raises:
        ValueError: If the reloaded model's predictions do not match the
            forecast contract.
    """
    model = load_joblib(model_path)
    return validate_predictions(
        model.predict(numeric_predictors(test_rows, manifest.selected_feature_columns)),
        expected_rows=len(test_rows),
        target_columns=list(manifest.target_columns),
        artifact_name="saved MLP sealed-test",
    )
