"""Ridge candidate selection, construction, and model manifest helpers."""

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from joblib import load as load_joblib  # type: ignore[import-untyped]
from sklearn.compose import (  # type: ignore[import-untyped]
    ColumnTransformer,
    TransformedTargetRegressor,
)
from sklearn.linear_model import Ridge  # type: ignore[import-untyped]
from sklearn.pipeline import Pipeline  # type: ignore[import-untyped]
from sklearn.preprocessing import (  # type: ignore[import-untyped]
    FunctionTransformer,
    StandardScaler,
)

from src.dataset import JoinedFeatureContract
from src.feature_engineering import log1p_eligible_columns
from src.model_selection import select_candidate as _select_candidate
from src.model_selection import tie_breaking_policy as _tie_breaking_policy
from src.training import numeric_predictors, validate_predictions

_TIE_BREAK_COLUMNS = ["feature_count", "log1p", "alpha", "subset"]
_TIE_BREAK_DESCRIPTIONS = [
    "fewer features",
    "log1p=False preferred",
    "smaller alpha",
    "stable subset name",
]

# Manifest layout written by this module. There is no back-compatible reader:
# a manifest from an older schema must be regenerated by re-running the notebook.
MANIFEST_SCHEMA_VERSION = "5.0"
MANIFEST_GUIDANCE = (
    "Run 04_02_train_ridge.ipynb through its sealed-test cell to write one."
)


def select_candidate(
    cv_results: pd.DataFrame, metric: str = "rmse"
) -> tuple[str, float, bool]:
    """Select one subset/alpha/log1p triple with deterministic tie-breaking.

    Args:
        cv_results: One row per candidate subset/alpha/log1p with mean CV
            metrics.
        metric: Ranking metric, either ``"mae"`` or ``"rmse"``.

    Returns:
        The winning candidate's subset name, alpha, and log1p flag.

    Raises:
        ValueError: If the metric is invalid, results are empty or missing
            required columns, or ranking values contain nulls.
    """
    winner = _select_candidate(cv_results, metric, tie_break_columns=_TIE_BREAK_COLUMNS)
    return str(winner["subset"]), float(winner["alpha"]), bool(winner["log1p"])


def tie_breaking_policy(selection_metric: str) -> list[str]:
    """Describe the candidate tie-breaking order :func:`select_candidate` applies.

    Args:
        selection_metric: Aggregate CV metric used to rank candidates.

    Returns:
        The ordered tie-breaking rules.
    """
    return _tie_breaking_policy(selection_metric, _TIE_BREAK_DESCRIPTIONS)


def build_ridge_estimator(
    feature_columns: Sequence[str], *, alpha: float, log1p: bool
) -> Pipeline | TransformedTargetRegressor:
    """Build one Ridge estimator, scaled and optionally log1p-transformed.

    The single construction path shared by the CV fold loop and the final
    retrain, so the saved model never diverges from what was cross-validated.

    Args:
        feature_columns: Ordered predictor columns the estimator is fitted on.
        alpha: Ridge L2 regularization strength.
        log1p: Whether to log1p-transform the log1p-eligible water-level
            predictors and the target before fitting.

    Returns:
        A plain ``Pipeline`` when ``log1p`` is False or no predictor is
        log1p-eligible; otherwise a ``TransformedTargetRegressor`` wrapping
        that pipeline so ``.predict()`` always returns raw-scale values.
    """
    feature_columns = list(feature_columns)
    level_columns = log1p_eligible_columns(feature_columns)
    other_columns = [
        column for column in feature_columns if column not in level_columns
    ]

    if log1p and level_columns:
        preprocessor = ColumnTransformer(
            [
                (
                    "log1p_scale",
                    Pipeline(
                        [
                            ("log1p", FunctionTransformer(np.log1p, validate=True)),
                            ("scale", StandardScaler()),
                        ]
                    ),
                    level_columns,
                ),
                ("scale", StandardScaler(), other_columns),
            ]
        )
        model = Pipeline([("preprocess", preprocessor), ("ridge", Ridge(alpha=alpha))])
        return TransformedTargetRegressor(
            regressor=model, func=np.log1p, inverse_func=np.expm1
        )

    preprocessor = ColumnTransformer([("scale", StandardScaler(), feature_columns)])
    return Pipeline([("preprocess", preprocessor), ("ridge", Ridge(alpha=alpha))])


@dataclass(frozen=True)
class RidgeManifest:
    """The durable record of one completed Ridge execution.

    Attributes:
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        station_id: Target station the model predicts.
        selected_subset: Name of the winning ablation subset.
        selected_alpha: Winning Ridge regularization strength.
        selected_log1p: Whether the winning candidate log1p-transformed the
            eligible water-level predictors and the target.
        selected_feature_columns: Ordered predictors the model was fitted on.
        target_columns: Ordered direct-forecast target columns.
    """

    execution_uuid: str
    station_id: str
    selected_subset: str
    selected_alpha: float
    selected_log1p: bool
    selected_feature_columns: tuple[str, ...]
    target_columns: tuple[str, ...]


def save_ridge_manifest(
    path: Path,
    *,
    model_path: Path,
    execution_uuid: str,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
    selected_subset: str,
    selected_alpha: float,
    selected_log1p: bool,
) -> None:
    """Write the model-only manifest for one fitted Ridge estimator.

    Args:
        path: Manifest JSON path to write.
        model_path: Saved Ridge joblib model path.
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        contract: Joined-feature contract the model was fitted against.
        feature_subsets: The named ablation subsets, in contract order.
        selected_subset: Name of the winning ablation subset.
        selected_alpha: Winning Ridge regularization strength.
        selected_log1p: Whether the winning candidate log1p-transformed the
            eligible water-level predictors and the target.

    Raises:
        ValueError: If the selected subset is unknown.
    """
    if selected_subset not in feature_subsets:
        raise ValueError(f"Selected subset {selected_subset!r} is not a known subset")
    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "model_path": str(model_path),
        "execution_uuid": execution_uuid,
        "model_type": (
            "sklearn.compose.TransformedTargetRegressor"
            if selected_log1p
            else "sklearn.pipeline.Pipeline"
        ),
        "estimator": "Ridge",
        "preprocessor": (
            "log1p+StandardScaler (eligible water-level columns), "
            "StandardScaler (remaining columns)"
            if selected_log1p
            else "StandardScaler"
        ),
        "station_id": contract.station_id,
        "forecast_horizon_hours": len(contract.target_columns),
        "selected_subset": selected_subset,
        "selected_feature_columns": list(feature_subsets[selected_subset]),
        "target_columns": list(contract.target_columns),
        "selected_alpha": float(selected_alpha),
        "selected_log1p": bool(selected_log1p),
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def load_ridge_manifest(
    path: Path,
    *,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
) -> RidgeManifest:
    """Load a Ridge manifest and check it against the current contract.

    Args:
        path: Manifest JSON path to read.
        contract: Current joined-feature contract for the target station.
        feature_subsets: Named feature subsets built from ``contract``.

    Returns:
        The validated manifest.

    Raises:
        FileNotFoundError: If no manifest exists.
        ValueError: If the manifest was written by another schema version, or
            disagrees with the current contract or subset definitions.
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing Ridge model manifest: {path}. {MANIFEST_GUIDANCE}"
        )
    manifest = json.loads(path.read_text(encoding="utf-8"))
    schema_version = manifest.get("schema_version")
    if schema_version != MANIFEST_SCHEMA_VERSION:
        raise ValueError(
            f"Ridge manifest schema version {schema_version!r} is not "
            f"{MANIFEST_SCHEMA_VERSION!r}. {MANIFEST_GUIDANCE}"
        )
    if manifest.get("station_id") != contract.station_id:
        raise ValueError(
            "Ridge manifest station_id does not match the current target station"
        )
    if manifest.get("forecast_horizon_hours") != len(contract.target_columns):
        raise ValueError(
            "Ridge manifest forecast horizon does not match the current contract"
        )
    if tuple(manifest.get("target_columns", ())) != contract.target_columns:
        raise ValueError(
            "Ridge manifest target contract does not match the current contract"
        )
    selected_subset = manifest.get("selected_subset")
    if selected_subset not in feature_subsets:
        raise ValueError(
            f"Ridge manifest selected subset {selected_subset!r} is not a subset of "
            "the current contract"
        )
    selected_feature_columns = tuple(manifest.get("selected_feature_columns", ()))
    if selected_feature_columns != tuple(feature_subsets[selected_subset]):
        raise ValueError(
            "Ridge manifest selected features do not match the selected subset contract"
        )
    return RidgeManifest(
        execution_uuid=str(manifest["execution_uuid"]),
        station_id=str(manifest["station_id"]),
        selected_subset=str(selected_subset),
        selected_alpha=float(manifest["selected_alpha"]),
        selected_log1p=bool(manifest["selected_log1p"]),
        selected_feature_columns=selected_feature_columns,
        target_columns=contract.target_columns,
    )


def score_saved_model(
    manifest: RidgeManifest,
    model_path: Path,
    test_rows: pd.DataFrame,
) -> np.ndarray:
    """Reload the saved Ridge model and score the sealed-test cohort.

    Args:
        manifest: Validated manifest describing the saved model.
        model_path: Saved Ridge joblib model path.
        test_rows: Eligible sealed-test rows to score.

    Returns:
        Validated sealed-test predictions ordered like the manifest's targets.

    Raises:
        ValueError: If the reloaded model's predictions do not match the
            forecast contract.
    """
    model = load_joblib(model_path)
    return validate_predictions(
        model.predict(numeric_predictors(test_rows, manifest.selected_feature_columns)),
        expected_rows=len(test_rows),
        target_columns=list(manifest.target_columns),
        artifact_name="saved Ridge sealed-test",
    )
