"""Ridge candidate selection and the saved-model manifest that records it."""

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from joblib import load as load_joblib  # type: ignore[import-untyped]
from sklearn.compose import (  # type: ignore[import-untyped]
    ColumnTransformer,
    TransformedTargetRegressor,
)
from sklearn.linear_model import Ridge  # type: ignore[import-untyped]
from sklearn.pipeline import Pipeline  # type: ignore[import-untyped]
from sklearn.preprocessing import (  # type: ignore[import-untyped]
    FunctionTransformer,
    StandardScaler,
)

from src.dataset import JoinedFeatureContract
from src.feature_engineering import log1p_eligible_columns
from src.training import numeric_predictors, validate_predictions

# Manifest layout written by this module. There is no back-compatible reader:
# a manifest from an older schema must be regenerated by re-running the notebook.
MANIFEST_SCHEMA_VERSION = "3.0"
# Aggregate sealed-test metrics every manifest must carry.
SEALED_TEST_METRIC_NAMES = ("test_mae", "test_rmse", "test_me", "test_r2")
MANIFEST_GUIDANCE = (
    "Run 04_02_train_ridge.ipynb through its sealed-test cell to write one."
)


def select_candidate(
    cv_results: pd.DataFrame, metric: str = "rmse"
) -> tuple[str, float, bool]:
    """Select one subset/alpha/log1p triple with deterministic tie-breaking.

    Args:
        cv_results: One row per candidate subset/alpha/log1p with mean CV
            metrics.
        metric: Ranking metric, either ``"mae"`` or ``"rmse"``.

    Returns:
        The winning candidate's subset name, alpha, and log1p flag.

    Raises:
        ValueError: If the metric is invalid, results are empty or missing
            required columns, or ranking values contain nulls.
    """
    if metric not in {"mae", "rmse"}:
        raise ValueError("CV selection metric must be either 'mae' or 'rmse'")
    metric_column = f"{metric}_mean"
    required_columns = {"subset", "alpha", "feature_count", "log1p", metric_column}
    missing = sorted(required_columns.difference(cv_results.columns))
    if missing or cv_results.empty:
        raise ValueError(f"CV results are empty or missing columns: {missing}")
    if (
        cv_results[[metric_column, "alpha", "feature_count", "log1p"]]
        .isna()
        .any()
        .any()
    ):
        raise ValueError("CV candidate results contain null ranking values")
    ranked = cv_results.sort_values(
        [metric_column, "feature_count", "log1p", "alpha", "subset"],
        kind="stable",
    )
    winner = ranked.iloc[0]
    return str(winner["subset"]), float(winner["alpha"]), bool(winner["log1p"])


def tie_breaking_policy(selection_metric: str) -> list[str]:
    """Describe the candidate tie-breaking order :func:`select_candidate` applies.

    Args:
        selection_metric: Aggregate CV metric used to rank candidates.

    Returns:
        The ordered tie-breaking rules, recorded in the saved manifest.
    """
    return [
        f"lowest aggregate CV {selection_metric.upper()}",
        "fewer features",
        "log1p=False preferred",
        "smaller alpha",
        "stable subset name",
    ]


def build_ridge_estimator(
    feature_columns: Sequence[str], *, alpha: float, log1p: bool
) -> Pipeline | TransformedTargetRegressor:
    """Build one Ridge estimator, scaled and optionally log1p-transformed.

    The single construction path shared by the CV fold loop and the final
    retrain, so the saved model never diverges from what was cross-validated.

    Args:
        feature_columns: Ordered predictor columns the estimator is fitted on.
        alpha: Ridge L2 regularization strength.
        log1p: Whether to log1p-transform the log1p-eligible water-level
            predictors and the target before fitting.

    Returns:
        A plain ``Pipeline`` when ``log1p`` is False or no predictor is
        log1p-eligible; otherwise a ``TransformedTargetRegressor`` wrapping
        that pipeline so ``.predict()`` always returns raw-scale values.
    """
    feature_columns = list(feature_columns)
    level_columns = log1p_eligible_columns(feature_columns)
    other_columns = [
        column for column in feature_columns if column not in level_columns
    ]

    if log1p and level_columns:
        preprocessor = ColumnTransformer(
            [
                (
                    "log1p_scale",
                    Pipeline(
                        [
                            ("log1p", FunctionTransformer(np.log1p, validate=True)),
                            ("scale", StandardScaler()),
                        ]
                    ),
                    level_columns,
                ),
                ("scale", StandardScaler(), other_columns),
            ]
        )
        model = Pipeline([("preprocess", preprocessor), ("ridge", Ridge(alpha=alpha))])
        return TransformedTargetRegressor(
            regressor=model, func=np.log1p, inverse_func=np.expm1
        )

    preprocessor = ColumnTransformer([("scale", StandardScaler(), feature_columns)])
    return Pipeline([("preprocess", preprocessor), ("ridge", Ridge(alpha=alpha))])


@dataclass(frozen=True)
class RidgeManifest:
    """The durable record of one completed Ridge execution.

    Attributes:
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        station_id: Target station the model predicts.
        selected_subset: Name of the winning ablation subset.
        selected_alpha: Winning Ridge regularization strength.
        selected_log1p: Whether the winning candidate log1p-transformed the
            eligible water-level predictors and the target.
        selection_metric: Aggregate CV metric used to rank candidates.
        selected_feature_columns: Ordered predictors the model was fitted on.
        target_columns: Ordered direct-forecast target columns.
        cv_results: One row per candidate subset/alpha/log1p with its CV
            metrics.
        sealed_test_metrics: Aggregate sealed-test MAE, RMSE, ME, and R².
        horizon_metrics: One sealed-test metric row per forecast horizon.
    """

    execution_uuid: str
    station_id: str
    selected_subset: str
    selected_alpha: float
    selected_log1p: bool
    selection_metric: str
    selected_feature_columns: tuple[str, ...]
    target_columns: tuple[str, ...]
    cv_results: pd.DataFrame
    sealed_test_metrics: dict[str, float]
    horizon_metrics: pd.DataFrame


def save_ridge_manifest(
    path: Path,
    *,
    model_path: Path,
    execution_uuid: str,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
    selected_subset: str,
    selected_alpha: float,
    selected_log1p: bool,
    selection_metric: str,
    cv_results: pd.DataFrame,
    sealed_test_metrics: Mapping[str, float],
    per_horizon_metrics: pd.DataFrame,
    cohort: Mapping[str, object],
    training: Mapping[str, object],
) -> None:
    """Write the manifest that records one completed Ridge execution.

    Called once, after the sealed test has been scored, so the manifest never
    describes a run that did not finish.

    Args:
        path: Manifest JSON path to write.
        model_path: Saved Ridge joblib model path.
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        contract: Joined-feature contract the model was fitted against.
        feature_subsets: The named ablation subsets, in contract order.
        selected_subset: Name of the winning ablation subset.
        selected_alpha: Winning Ridge regularization strength.
        selected_log1p: Whether the winning candidate log1p-transformed the
            eligible water-level predictors and the target.
        selection_metric: Aggregate CV metric used to rank candidates.
        cv_results: One row per candidate subset/alpha/log1p with its CV
            metrics.
        sealed_test_metrics: Aggregate sealed-test MAE, RMSE, ME, and R².
        per_horizon_metrics: Sealed-test metric rows keyed by horizon, as
            returned by :func:`src.metrics.metric_tables`.
        cohort: Common-cohort eligibility provenance.
        training: Training-artifact and time-range provenance.

    Raises:
        ValueError: If the selected subset is unknown, an aggregate sealed-test
            metric is missing or non-finite, or the per-horizon metrics do not
            cover the forecast contract exactly once.
    """
    if selected_subset not in feature_subsets:
        raise ValueError(f"Selected subset {selected_subset!r} is not a known subset")
    missing_metrics = sorted(
        set(SEALED_TEST_METRIC_NAMES).difference(sealed_test_metrics)
    )
    if missing_metrics:
        raise ValueError(f"Sealed-test metrics are missing: {missing_metrics}")
    if not all(
        np.isfinite(float(sealed_test_metrics[name]))
        for name in SEALED_TEST_METRIC_NAMES
    ):
        raise ValueError("Sealed-test metrics contain non-finite values")
    horizon_records = _horizon_records(per_horizon_metrics, contract)

    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "model_path": str(model_path),
        "execution_uuid": execution_uuid,
        "model_type": (
            "sklearn.compose.TransformedTargetRegressor"
            if selected_log1p
            else "sklearn.pipeline.Pipeline"
        ),
        "estimator": "Ridge",
        "preprocessor": (
            "log1p+StandardScaler (eligible water-level columns), "
            "StandardScaler (remaining columns)"
            if selected_log1p
            else "StandardScaler"
        ),
        "station_id": contract.station_id,
        "forecast_horizon_hours": len(contract.target_columns),
        "full_feature_columns": list(contract.predictor_columns),
        "selected_subset": selected_subset,
        "selected_feature_columns": list(feature_subsets[selected_subset]),
        "feature_subsets": {
            name: list(columns) for name, columns in feature_subsets.items()
        },
        "target_columns": list(contract.target_columns),
        "selected_alpha": float(selected_alpha),
        "selected_log1p": bool(selected_log1p),
        "selection_metric": selection_metric,
        "tie_breaking": tie_breaking_policy(selection_metric),
        "cv_results": _cv_results_records(cv_results),
        "sealed_test_metrics": {
            name: float(sealed_test_metrics[name]) for name in SEALED_TEST_METRIC_NAMES
        },
        "horizon_metrics": horizon_records,
        "common_cohort_eligibility": dict(cohort),
        "training": dict(training),
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def load_ridge_manifest(
    path: Path,
    *,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
) -> RidgeManifest:
    """Load a Ridge manifest and check it against the current contract.

    Args:
        path: Manifest JSON path to read.
        contract: Current joined-feature contract for the target station.
        feature_subsets: Named feature subsets built from ``contract``.

    Returns:
        The validated manifest.

    Raises:
        FileNotFoundError: If no manifest exists.
        ValueError: If the manifest was written by another schema version, or
            disagrees with the current contract or subset definitions.
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing Ridge model manifest: {path}. {MANIFEST_GUIDANCE}"
        )
    manifest = json.loads(path.read_text(encoding="utf-8"))
    schema_version = manifest.get("schema_version")
    if schema_version != MANIFEST_SCHEMA_VERSION:
        raise ValueError(
            f"Ridge manifest schema version {schema_version!r} is not "
            f"{MANIFEST_SCHEMA_VERSION!r}. {MANIFEST_GUIDANCE}"
        )
    if manifest.get("station_id") != contract.station_id:
        raise ValueError(
            "Ridge manifest station_id does not match the current target station"
        )
    if manifest.get("forecast_horizon_hours") != len(contract.target_columns):
        raise ValueError(
            "Ridge manifest forecast horizon does not match the current contract"
        )
    if tuple(manifest.get("full_feature_columns", ())) != contract.predictor_columns:
        raise ValueError(
            "Ridge manifest full feature contract does not match the current contract"
        )
    if tuple(manifest.get("target_columns", ())) != contract.target_columns:
        raise ValueError(
            "Ridge manifest target contract does not match the current contract"
        )
    selected_subset = manifest.get("selected_subset")
    if selected_subset not in feature_subsets:
        raise ValueError(
            f"Ridge manifest selected subset {selected_subset!r} is not a subset of "
            "the current contract"
        )
    selected_feature_columns = tuple(manifest.get("selected_feature_columns", ()))
    if selected_feature_columns != tuple(feature_subsets[selected_subset]):
        raise ValueError(
            "Ridge manifest selected features do not match the selected subset contract"
        )
    return RidgeManifest(
        execution_uuid=str(manifest["execution_uuid"]),
        station_id=str(manifest["station_id"]),
        selected_subset=str(selected_subset),
        selected_alpha=float(manifest["selected_alpha"]),
        selected_log1p=bool(manifest["selected_log1p"]),
        selection_metric=str(manifest["selection_metric"]),
        selected_feature_columns=selected_feature_columns,
        target_columns=contract.target_columns,
        cv_results=pd.DataFrame(manifest["cv_results"]),
        sealed_test_metrics={
            name: float(manifest["sealed_test_metrics"][name])
            for name in SEALED_TEST_METRIC_NAMES
        },
        horizon_metrics=pd.DataFrame(manifest["horizon_metrics"]),
    )


def score_saved_model(
    manifest: RidgeManifest,
    model_path: Path,
    test_rows: pd.DataFrame,
) -> np.ndarray:
    """Reload the saved Ridge model and score the sealed-test cohort.

    Args:
        manifest: Validated manifest describing the saved model.
        model_path: Saved Ridge joblib model path.
        test_rows: Eligible sealed-test rows to score.

    Returns:
        Validated sealed-test predictions ordered like the manifest's targets.

    Raises:
        ValueError: If the reloaded model's predictions do not match the
            forecast contract.
    """
    model = load_joblib(model_path)
    return validate_predictions(
        model.predict(numeric_predictors(test_rows, manifest.selected_feature_columns)),
        expected_rows=len(test_rows),
        target_columns=list(manifest.target_columns),
        artifact_name="saved Ridge sealed-test",
    )


def _cv_results_records(cv_results: pd.DataFrame) -> list[dict[str, object]]:
    """Convert the candidate table to JSON-safe records.

    Args:
        cv_results: One row per candidate subset/alpha/log1p with its CV
            metrics.

    Returns:
        One record per candidate, with plain string, int, bool, and float
        values.
    """
    return [
        {
            str(key): (
                str(value)
                if key == "subset"
                else int(value)
                if key == "feature_count"
                else bool(value)
                if key == "log1p"
                else float(value)
            )
            for key, value in record.items()
        }
        for record in cv_results.to_dict(orient="records")
    ]


def _horizon_records(
    per_horizon_metrics: pd.DataFrame,
    contract: JoinedFeatureContract,
) -> list[dict[str, object]]:
    """Convert per-horizon sealed-test metrics to JSON-safe records.

    Args:
        per_horizon_metrics: Sealed-test metric rows keyed by horizon.
        contract: Joined-feature contract defining the expected horizons.

    Returns:
        One ``test_``-prefixed metric record per forecast horizon, in order.

    Raises:
        ValueError: If the horizons do not cover the forecast contract exactly
            once, or a metric is missing or non-finite.
    """
    expected_horizons = list(range(1, len(contract.target_columns) + 1))
    missing_columns = sorted(
        {"horizon_hours", "mae", "rmse", "me", "r2"}.difference(
            per_horizon_metrics.columns
        )
    )
    if missing_columns:
        raise ValueError(
            f"Sealed-test horizon metrics are missing columns: {missing_columns}"
        )
    if per_horizon_metrics["horizon_hours"].tolist() != expected_horizons:
        raise ValueError(
            "Sealed-test horizon metrics do not match the forecast contract"
        )
    records: list[dict[str, object]] = []
    for horizon, row in zip(
        expected_horizons, per_horizon_metrics.itertuples(), strict=True
    ):
        values = {
            f"test_{metric}": float(getattr(row, metric))
            for metric in ("mae", "rmse", "me", "r2")
        }
        if not all(np.isfinite(value) for value in values.values()):
            raise ValueError("Sealed-test horizon metrics contain non-finite values")
        records.append({"horizon_hours": horizon, **values})
    return records
