"""RNN candidate selection, construction, and model manifest helpers."""

import json
import random
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from joblib import load as load_joblib  # type: ignore[import-untyped]
from sklearn.preprocessing import StandardScaler  # type: ignore[import-untyped]
from torch import nn

from src.config import RANDOM_STATE
from src.dataset import JoinedFeatureContract
from src.model_selection import select_candidate as _select_candidate
from src.model_selection import tie_breaking_policy as _tie_breaking_policy
from src.training import validate_predictions

# Manifest layout written by this module. There is no back-compatible reader:
# a manifest from an older schema must be regenerated by re-running the notebook.
MANIFEST_SCHEMA_VERSION = "4.0"
MANIFEST_GUIDANCE = (
    "Run 04_07_train_rnn.ipynb through its sealed-test cell to write one."
)

_TIE_BREAK_COLUMNS = [
    "channel_count",
    "sequence_length",
    "hidden_size",
    "num_layers",
    "cell_type",
    "subset",
]
_TIE_BREAK_DESCRIPTIONS = [
    "fewer channels",
    "shorter sequence_length",
    "smaller hidden_size",
    "fewer num_layers",
    "stable cell_type name",
    "stable subset name",
]

# Ordered candidate key: the feature subset crossed with one sampled draw.
CANDIDATE_COLUMNS = [
    "subset",
    "cell_type",
    "sequence_length",
    "hidden_size",
    "num_layers",
]


def load_raw_channel_frame(
    path: Path, *, channel_columns: Sequence[str]
) -> pd.DataFrame:
    """Load the raw per-timestep channel frame from a joined feature artifact.

    Reads a joined Stage-3 Parquet (train or test) and keeps ``timestamp``
    plus ``channel_columns``, independent of ``load_joined_dataset``'s
    row-level eligibility filtering, so a sequence lookback window can read
    hours that fail today's target-valid/complete-predictor gate.

    Args:
        path: Joined feature Parquet path to read.
        channel_columns: Ordered raw per-timestep channel columns to keep.

    Returns:
        The channel frame, timestamp-indexed in ascending order.

    Raises:
        FileNotFoundError: If ``path`` does not exist.
        ValueError: If a channel column is missing, or timestamps are not
            unique, ascending, and a contiguous hourly grid.
    """
    if not path.is_file():
        raise FileNotFoundError(f"Missing joined feature artifact: {path}")
    channel_columns = list(channel_columns)
    frame = pd.read_parquet(path)
    missing = sorted({"timestamp", *channel_columns}.difference(frame.columns))
    if missing:
        raise ValueError(f"Raw channel frame is missing required columns: {missing}")

    timestamps = pd.DatetimeIndex(pd.to_datetime(frame["timestamp"], utc=True))
    if timestamps.has_duplicates or not timestamps.is_monotonic_increasing:
        raise ValueError("Raw channel frame timestamps must be unique and increasing")
    expected_grid = pd.date_range(timestamps[0], periods=len(timestamps), freq="h")
    if not timestamps.equals(expected_grid):
        raise ValueError(
            "Raw channel frame timestamps must be a contiguous hourly grid"
        )
    return frame[channel_columns].set_index(timestamps)


def build_sequences(
    raw_channel_frame: pd.DataFrame,
    candidate_rows: pd.DataFrame,
    *,
    sequence_length: int,
    channel_columns: Sequence[str],
    target_columns: Sequence[str],
    artifact_name: str,
) -> tuple[np.ndarray, np.ndarray, pd.DataFrame]:
    """Build split-local sequence windows for already-eligible issue times.

    ``candidate_rows`` (``dataset.train_rows``/``test_rows``) already satisfy
    ``load_joined_dataset``'s eligibility. This narrows that cohort further: a
    row at timestamp ``t`` is kept only when at least ``sequence_length``
    hours of this split's own raw channel history exist before and including
    ``t`` (never reaching into the other split), and every channel value is
    finite across the whole window. Imputed-but-present hours are fine;
    genuinely missing ones are not.

    Args:
        raw_channel_frame: Timestamp-indexed raw channel frame for this split,
            from :func:`load_raw_channel_frame`.
        candidate_rows: Eligible rows (``dataset.train_rows``/``test_rows``)
            to narrow further by sequence completeness.
        sequence_length: Number of hourly timesteps in each window.
        channel_columns: Ordered raw per-timestep channel columns.
        target_columns: Ordered direct-forecast target columns.
        artifact_name: Human-readable artifact label used in errors.

    Returns:
        A tuple of ``sequences`` (float64, shape ``(n_eligible,
        sequence_length, len(channel_columns))``), ``targets`` (float64,
        shape ``(n_eligible, len(target_columns))``), and ``origins`` (the
        subset of ``candidate_rows`` with a complete window, in chronological
        order with a fresh ``RangeIndex``). ``len(origins) <=
        len(candidate_rows)``.

    Raises:
        ValueError: If ``sequence_length < 1``, a required column is missing,
            or no candidate row has a complete window.
    """
    if sequence_length < 1:
        raise ValueError("sequence_length must be at least 1")
    channel_columns = list(channel_columns)
    target_columns = list(target_columns)
    missing_channels = sorted(
        set(channel_columns).difference(raw_channel_frame.columns)
    )
    if missing_channels:
        raise ValueError(f"Raw channel frame is missing columns: {missing_channels}")
    missing_targets = sorted(set(target_columns).difference(candidate_rows.columns))
    if missing_targets:
        raise ValueError(
            f"Candidate rows are missing target columns: {missing_targets}"
        )

    candidate_timestamps = pd.DatetimeIndex(
        pd.to_datetime(candidate_rows["timestamp"], utc=True)
    )
    positions = raw_channel_frame.index.get_indexer(candidate_timestamps)
    finite_rows = pd.Series(
        np.isfinite(raw_channel_frame[channel_columns].to_numpy(dtype=float)).all(
            axis=1
        ),
        index=raw_channel_frame.index,
    )
    complete_windows = (
        finite_rows.rolling(sequence_length, min_periods=sequence_length)
        .sum()
        .eq(sequence_length)
        .to_numpy()
    )
    safe_positions = np.clip(positions, 0, len(complete_windows) - 1)
    eligible = (positions >= sequence_length - 1) & complete_windows[safe_positions]
    eligible_positions = np.flatnonzero(eligible)
    if not len(eligible_positions):
        raise ValueError(
            f"{artifact_name} has no eligible {sequence_length}-hour sequences"
        )

    channel_values = raw_channel_frame[channel_columns].to_numpy(dtype=float)
    origin_positions = positions[eligible_positions]
    sequences = np.stack(
        [
            channel_values[position - sequence_length + 1 : position + 1]
            for position in origin_positions
        ]
    )
    origins = candidate_rows.iloc[eligible_positions].reset_index(drop=True)
    targets = origins[target_columns].to_numpy(dtype=float)
    return sequences, targets, origins


def subset_channel_indices(
    cohort_channel_columns: Sequence[str], channel_columns: Sequence[str]
) -> list[int]:
    """Locate a feature subset's channels inside the cohort channel axis.

    Sequences are built once with the cohort channels (the ``full`` subset,
    so every subset shares the same sequence-eligible rows) and then sliced
    along the channel axis with these indices.

    Args:
        cohort_channel_columns: Ordered channels the sequences were built with.
        channel_columns: Ordered channels of one feature subset.

    Returns:
        Channel-axis indices of ``channel_columns``, in their given order.

    Raises:
        ValueError: If the subset is empty, contains duplicates, or is not an
            order-preserving subsequence of the cohort channels.
    """
    cohort_positions = {
        column: position for position, column in enumerate(cohort_channel_columns)
    }
    channel_columns = list(channel_columns)
    if not channel_columns or len(channel_columns) != len(set(channel_columns)):
        raise ValueError("Subset channel columns must be non-empty and unique")
    missing = [column for column in channel_columns if column not in cohort_positions]
    if missing:
        raise ValueError(f"Subset channels are not cohort channels: {missing}")
    indices = [cohort_positions[column] for column in channel_columns]
    if indices != sorted(indices):
        raise ValueError("Subset channels must preserve the cohort channel order")
    return indices


class _RecurrentForecaster(nn.Module):
    """One-layer-or-more direct multi-horizon GRU or LSTM forecaster."""

    def __init__(
        self,
        *,
        cell_type: str,
        input_size: int,
        hidden_size: int,
        num_layers: int,
        dropout: float,
        forecast_horizon: int,
    ) -> None:
        """Build the recurrent encoder and the multi-horizon linear head."""
        super().__init__()
        recurrent_class = nn.GRU if cell_type == "gru" else nn.LSTM
        self.recurrent = recurrent_class(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            dropout=dropout if num_layers > 1 else 0.0,
            batch_first=True,
        )
        self.head = nn.Linear(hidden_size, forecast_horizon)

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        """Predict all forecast horizons from the final recurrent step."""
        outputs, _ = self.recurrent(inputs)
        result: torch.Tensor = self.head(outputs[:, -1, :])
        return result


class RnnForecaster:
    """Thin sklearn-Estimator-shaped wrapper around a torch GRU/LSTM.

    Owns the torch ``nn.Module``, a channel ``StandardScaler`` fit on
    flattened ``(n * L, C)`` training values, a target ``StandardScaler`` fit
    on ``(n, H)`` training targets, and the training loop. The whole fitted
    object round-trips through ``joblib.dump``/``load`` like Ridge's
    ``Pipeline`` or MLP's ``TransformedTargetRegressor``. ``.fit``/``.predict``
    take and return plain numpy arrays, not DataFrames.
    """

    def __init__(
        self,
        *,
        cell_type: str,
        hidden_size: int,
        num_layers: int,
        dropout: float = 0.1,
        learning_rate: float = 0.001,
        max_epochs: int = 50,
        batch_size: int = 64,
        random_state: int = RANDOM_STATE,
        device: str | None = None,
    ) -> None:
        """Store hyperparameters; nothing is fitted until :meth:`fit` runs."""
        if cell_type not in {"gru", "lstm"}:
            raise ValueError(f"cell_type must be 'gru' or 'lstm'; got {cell_type!r}")
        self.cell_type = cell_type
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.dropout = dropout
        self.learning_rate = learning_rate
        self.max_epochs = max_epochs
        self.batch_size = batch_size
        self.random_state = random_state
        self.device = device
        self.module_: _RecurrentForecaster | None = None
        self.channel_scaler_: StandardScaler | None = None
        self.target_scaler_: StandardScaler | None = None
        self.epoch_losses_: list[float] = []

    def fit(self, sequences: np.ndarray, targets: np.ndarray) -> "RnnForecaster":
        """Seed every RNG, fit fresh scalers, train from scratch, move to CPU.

        Args:
            sequences: Training windows, shape ``(n, sequence_length,
                n_channels)``.
            targets: Training targets, shape ``(n, forecast_horizon)``.

        Returns:
            ``self``, with the trained module always moved to CPU so the
            fitted object is joblib-picklable/portable regardless of the
            accelerator used during training.
        """
        random.seed(self.random_state)
        np.random.seed(self.random_state)
        torch.manual_seed(self.random_state)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(self.random_state)

        device = torch.device(self.device or _auto_device())
        n_samples, sequence_length, n_channels = sequences.shape
        forecast_horizon = targets.shape[1]

        self.channel_scaler_ = StandardScaler()
        scaled_channels = self.channel_scaler_.fit_transform(
            sequences.reshape(-1, n_channels)
        ).reshape(n_samples, sequence_length, n_channels)
        self.target_scaler_ = StandardScaler()
        scaled_targets = self.target_scaler_.fit_transform(targets)

        module = _RecurrentForecaster(
            cell_type=self.cell_type,
            input_size=n_channels,
            hidden_size=self.hidden_size,
            num_layers=self.num_layers,
            dropout=self.dropout,
            forecast_horizon=forecast_horizon,
        ).to(device)
        optimizer = torch.optim.Adam(module.parameters(), lr=self.learning_rate)
        loss_function = nn.MSELoss()

        # The whole training set lives on the device and is sliced per batch;
        # a per-sample DataLoader plus a per-step host sync dominate runtime
        # for these small recurrent modules.
        channel_tensor = torch.tensor(
            scaled_channels, dtype=torch.float32, device=device
        )
        target_tensor = torch.tensor(scaled_targets, dtype=torch.float32, device=device)
        # Same CPU generator and draw as DataLoader(shuffle=True)'s
        # RandomSampler, so every epoch sees the same batch composition.
        shuffle_generator = torch.Generator().manual_seed(self.random_state)

        epoch_losses: list[float] = []
        for _ in range(self.max_epochs):
            module.train()
            # Mirror DataLoader's per-epoch draws from its generator: a base
            # seed when the iterator starts, the permutation, and a second
            # permutation RandomSampler draws and truncates to zero length.
            torch.empty((), dtype=torch.int64).random_(generator=shuffle_generator)
            permutation = torch.randperm(n_samples, generator=shuffle_generator).to(
                device
            )
            torch.randperm(n_samples, generator=shuffle_generator)
            weighted_loss = torch.zeros((), device=device)
            for start in range(0, n_samples, self.batch_size):
                batch_indices = permutation[start : start + self.batch_size]
                batch_sequences = channel_tensor[batch_indices]
                batch_targets = target_tensor[batch_indices]
                optimizer.zero_grad()
                loss = loss_function(module(batch_sequences), batch_targets)
                loss.backward()
                optimizer.step()
                weighted_loss += loss.detach() * len(batch_indices)
            epoch_losses.append(float(weighted_loss) / n_samples)

        self.module_ = module.to("cpu")
        self.epoch_losses_ = epoch_losses
        return self

    def predict(self, sequences: np.ndarray) -> np.ndarray:
        """Scale, run CPU inference, inverse-transform to raw units.

        Args:
            sequences: Windows to score, shape ``(n, sequence_length,
                n_channels)``.

        Returns:
            A finite float64 array, shape ``(len(sequences),
            forecast_horizon)``.

        Raises:
            ValueError: If the estimator has not been fitted.
        """
        if (
            self.module_ is None
            or self.channel_scaler_ is None
            or self.target_scaler_ is None
        ):
            raise ValueError("RnnForecaster must be fitted before predicting")
        n_samples, sequence_length, n_channels = sequences.shape
        scaled_channels = self.channel_scaler_.transform(
            sequences.reshape(-1, n_channels)
        ).reshape(n_samples, sequence_length, n_channels)
        self.module_.eval()
        with torch.no_grad():
            scaled_predictions = self.module_(
                torch.tensor(scaled_channels, dtype=torch.float32)
            ).numpy()
        predictions: np.ndarray = self.target_scaler_.inverse_transform(
            scaled_predictions
        )
        return predictions.astype(np.float64)


def _auto_device() -> str:
    """Return the first available of MPS, CUDA, or CPU."""
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"


def build_rnn_estimator(
    *,
    cell_type: str,
    sequence_length: int,
    hidden_size: int,
    num_layers: int,
    dropout: float = 0.1,
    learning_rate: float = 0.001,
    max_epochs: int = 50,
    batch_size: int = 64,
    random_state: int = RANDOM_STATE,
    device: str | None = None,
) -> RnnForecaster:
    """Build one unfitted RnnForecaster.

    The single construction path shared by every CV fold and the final
    retrain, so the saved model never diverges from what was
    cross-validated (same rationale as ``build_ridge_estimator`` /
    ``build_mlp_estimator``).

    Args:
        cell_type: Recurrent cell type, ``"gru"`` or ``"lstm"``.
        sequence_length: Recorded for parity with Ridge/MLP's
            ``build_*_estimator`` convention; not consumed by the module
            (already baked into the sequences passed to ``.fit``/``.predict``).
        hidden_size: Width of the recurrent hidden state.
        num_layers: Number of stacked recurrent layers.
        dropout: Inter-layer dropout (a no-op when ``num_layers == 1``).
        learning_rate: Adam's step size.
        max_epochs: Fixed training-epoch budget.
        batch_size: Minibatch size.
        random_state: Seed for weight initialization and the per-epoch
            shuffle order.
        device: Torch device to train on; ``None`` auto-detects MPS/CUDA/CPU.

    Returns:
        An unfitted :class:`RnnForecaster`.
    """
    del sequence_length
    return RnnForecaster(
        cell_type=cell_type,
        hidden_size=hidden_size,
        num_layers=num_layers,
        dropout=dropout,
        learning_rate=learning_rate,
        max_epochs=max_epochs,
        batch_size=batch_size,
        random_state=random_state,
        device=device,
    )


def sampled_parameter_key(params: Mapping[str, object]) -> tuple[str, int, int, int]:
    """Return the canonical hyperparameter key of one sampled draw.

    Args:
        params: One ``ParameterSampler`` draw.

    Returns:
        ``(cell_type, sequence_length, hidden_size, num_layers)``.
    """
    return (
        str(params["cell_type"]),
        int(params["sequence_length"]),  # type: ignore[call-overload]
        int(params["hidden_size"]),  # type: ignore[call-overload]
        int(params["num_layers"]),  # type: ignore[call-overload]
    )


def select_candidate(
    cv_results: pd.DataFrame, metric: str = "rmse"
) -> tuple[str, str, int, int, int]:
    """Select one subset/cell_type/sequence_length/hidden_size/num_layers candidate.

    Args:
        cv_results: One row per candidate with mean CV metrics and a
            ``channel_count`` column.
        metric: Ranking metric, either ``"mae"`` or ``"rmse"``.

    Returns:
        The winning candidate's ``(subset, cell_type,
        sequence_length, hidden_size, num_layers)``, in
        :data:`CANDIDATE_COLUMNS` order.

    Raises:
        ValueError: If the metric is invalid, results are empty or missing
            required columns, or ranking values contain nulls.
    """
    winner = _select_candidate(cv_results, metric, tie_break_columns=_TIE_BREAK_COLUMNS)
    return (
        str(winner["subset"]),
        str(winner["cell_type"]),
        int(winner["sequence_length"]),
        int(winner["hidden_size"]),
        int(winner["num_layers"]),
    )


def tie_breaking_policy(selection_metric: str) -> list[str]:
    """Describe the candidate tie-breaking order :func:`select_candidate` applies.

    Args:
        selection_metric: Aggregate CV metric used to rank candidates.

    Returns:
        The ordered tie-breaking rules.
    """
    return _tie_breaking_policy(selection_metric, _TIE_BREAK_DESCRIPTIONS)


@dataclass(frozen=True)
class RnnManifest:
    """The durable record of one completed RNN execution.

    Attributes:
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        station_id: Target station the model predicts.
        selected_subset: Winning feature subset the channels come from.
        selected_cell_type: Winning recurrent cell type.
        selected_sequence_length: Winning lookback window length, in hours.
        selected_hidden_size: Winning recurrent hidden-state width.
        selected_num_layers: Winning number of stacked recurrent layers.
        fixed_dropout: Fixed inter-layer dropout used by every candidate.
        channel_columns: Ordered per-timestep channels the model reads.
        target_columns: Ordered direct-forecast target columns.
    """

    execution_uuid: str
    station_id: str
    selected_subset: str
    selected_cell_type: str
    selected_sequence_length: int
    selected_hidden_size: int
    selected_num_layers: int
    fixed_dropout: float
    channel_columns: tuple[str, ...]
    target_columns: tuple[str, ...]


def save_rnn_manifest(
    path: Path,
    *,
    model_path: Path,
    execution_uuid: str,
    contract: JoinedFeatureContract,
    channel_columns: Sequence[str],
    selected_subset: str,
    selected_cell_type: str,
    selected_sequence_length: int,
    selected_hidden_size: int,
    selected_num_layers: int,
    fixed_dropout: float,
) -> None:
    """Write the model-only manifest for one fitted RNN estimator.

    Args:
        path: Manifest JSON path to write.
        model_path: Saved RNN joblib model path.
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        contract: Joined-feature contract the model was fitted against.
        channel_columns: Ordered per-timestep channels the model reads.
        selected_subset: Winning feature subset the channels come from.
        selected_cell_type: Winning recurrent cell type.
        selected_sequence_length: Winning lookback window length, in hours.
        selected_hidden_size: Winning recurrent hidden-state width.
        selected_num_layers: Winning number of stacked recurrent layers.
        fixed_dropout: Fixed inter-layer dropout used by every candidate.
    """
    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "model_path": str(model_path),
        "execution_uuid": execution_uuid,
        "model_type": "src.rnn.RnnForecaster",
        "estimator": "nn.GRU/nn.LSTM + nn.Linear head",
        "preprocessor": "StandardScaler (channels), StandardScaler (target)",
        "station_id": contract.station_id,
        "forecast_horizon_hours": len(contract.target_columns),
        "channel_columns": list(channel_columns),
        "target_columns": list(contract.target_columns),
        "selected_subset": selected_subset,
        "selected_cell_type": selected_cell_type,
        "selected_sequence_length": int(selected_sequence_length),
        "selected_hidden_size": int(selected_hidden_size),
        "selected_num_layers": int(selected_num_layers),
        "fixed_dropout": float(fixed_dropout),
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def load_rnn_manifest(
    path: Path,
    *,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
) -> RnnManifest:
    """Load an RNN manifest and check it against the current contract.

    Args:
        path: Manifest JSON path to read.
        contract: Current joined-feature contract for the target station.
        feature_subsets: Current ``dataset.feature_subsets``; the manifest's
            channels must equal its selected subset's columns.

    Returns:
        The validated manifest.

    Raises:
        FileNotFoundError: If no manifest exists.
        ValueError: If the manifest was written by another schema version, or
            disagrees with the current contract or its feature subset.
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing RNN model manifest: {path}. {MANIFEST_GUIDANCE}"
        )
    manifest = json.loads(path.read_text(encoding="utf-8"))
    schema_version = manifest.get("schema_version")
    if schema_version != MANIFEST_SCHEMA_VERSION:
        raise ValueError(
            f"RNN manifest schema version {schema_version!r} is not "
            f"{MANIFEST_SCHEMA_VERSION!r}. {MANIFEST_GUIDANCE}"
        )
    if manifest.get("station_id") != contract.station_id:
        raise ValueError(
            "RNN manifest station_id does not match the current target station"
        )
    if manifest.get("forecast_horizon_hours") != len(contract.target_columns):
        raise ValueError(
            "RNN manifest forecast horizon does not match the current contract"
        )
    if tuple(manifest.get("target_columns", ())) != contract.target_columns:
        raise ValueError(
            "RNN manifest target contract does not match the current contract"
        )
    selected_subset = manifest.get("selected_subset")
    if selected_subset not in feature_subsets:
        raise ValueError(
            f"RNN manifest feature subset {selected_subset!r} is not a "
            "current feature subset"
        )
    if tuple(manifest.get("channel_columns", ())) != tuple(
        feature_subsets[selected_subset]
    ):
        raise ValueError(
            "RNN manifest channel columns do not match the current "
            f"{selected_subset!r} subset"
        )
    return RnnManifest(
        execution_uuid=str(manifest["execution_uuid"]),
        station_id=str(manifest["station_id"]),
        selected_subset=str(selected_subset),
        selected_cell_type=str(manifest["selected_cell_type"]),
        selected_sequence_length=int(manifest["selected_sequence_length"]),
        selected_hidden_size=int(manifest["selected_hidden_size"]),
        selected_num_layers=int(manifest["selected_num_layers"]),
        fixed_dropout=float(manifest["fixed_dropout"]),
        channel_columns=tuple(manifest["channel_columns"]),
        target_columns=contract.target_columns,
    )


def score_saved_model(
    manifest: RnnManifest,
    model_path: Path,
    test_rows: pd.DataFrame,
    raw_test_channel_frame: pd.DataFrame,
    *,
    cohort_channel_columns: Sequence[str],
) -> tuple[np.ndarray, pd.DataFrame]:
    """Reload the saved RNN, rebuild sequences, and score the sealed test.

    Args:
        manifest: Validated manifest describing the saved model.
        model_path: Saved RNN joblib model path.
        test_rows: Eligible sealed-test rows (``dataset.test_rows``).
        raw_test_channel_frame: Per-timestep test-split channel frame, from
            :func:`load_raw_channel_frame`, holding ``cohort_channel_columns``.
        cohort_channel_columns: Channels that define sequence eligibility
            (``dataset.feature_subsets["full"]``), so the scored cohort matches
            training's common cohort whichever subset was selected.

    Returns:
        A tuple of ``(predictions, origins)``. The returned row count is NOT
        ``len(test_rows)``: only rows with a complete
        ``manifest.selected_sequence_length``-hour window across every cohort
        channel are scored.
        Downstream metric/plot calls must use ``origins``, not ``test_rows``,
        as their ``actual`` frame.

    Raises:
        ValueError: If the reloaded model's predictions do not match the
            forecast contract.
    """
    sequences, _targets, origins = build_sequences(
        raw_test_channel_frame,
        test_rows,
        sequence_length=manifest.selected_sequence_length,
        channel_columns=cohort_channel_columns,
        target_columns=list(manifest.target_columns),
        artifact_name="saved RNN sealed-test",
    )
    sequences = sequences[
        :, :, subset_channel_indices(cohort_channel_columns, manifest.channel_columns)
    ]
    model = load_joblib(model_path)
    predictions = validate_predictions(
        model.predict(sequences),
        expected_rows=len(origins),
        target_columns=list(manifest.target_columns),
        artifact_name="saved RNN sealed-test",
    )
    return predictions, origins
