"""RNN (LSTM/GRU) candidate selection and the saved-model manifest that records it."""

import json
import random
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from joblib import load as load_joblib  # type: ignore[import-untyped]
from sklearn.preprocessing import StandardScaler  # type: ignore[import-untyped]
from torch import nn
from torch.utils.data import DataLoader, TensorDataset

from src.config import RANDOM_STATE
from src.dataset import JoinedFeatureContract
from src.model_selection import select_candidate as _select_candidate
from src.model_selection import tie_breaking_policy as _tie_breaking_policy
from src.training import validate_predictions

# Manifest layout written by this module. There is no back-compatible reader:
# a manifest from an older schema must be regenerated by re-running the notebook.
MANIFEST_SCHEMA_VERSION = "1.0"
# Aggregate sealed-test metrics every manifest must carry.
SEALED_TEST_METRIC_NAMES = ("test_mae", "test_rmse", "test_me", "test_r2")
MANIFEST_GUIDANCE = (
    "Run 04_07_train_rnn.ipynb through its sealed-test cell to write one."
)

_TIE_BREAK_COLUMNS = ["sequence_length", "hidden_size", "num_layers", "cell_type"]
_TIE_BREAK_DESCRIPTIONS = [
    "shorter sequence_length",
    "smaller hidden_size",
    "fewer num_layers",
    "stable cell_type name",
]


def load_raw_channel_frame(
    path: Path, *, channel_columns: Sequence[str]
) -> pd.DataFrame:
    """Load the raw per-timestep channel frame from a joined feature artifact.

    Reads a joined Stage-3 Parquet (train or test) and keeps ``timestamp``
    plus ``channel_columns``, independent of ``load_joined_dataset``'s
    row-level eligibility filtering, so a sequence lookback window can read
    hours that fail today's target-valid/complete-predictor gate.

    Args:
        path: Joined feature Parquet path to read.
        channel_columns: Ordered raw per-timestep channel columns to keep.

    Returns:
        The channel frame, timestamp-indexed in ascending order.

    Raises:
        FileNotFoundError: If ``path`` does not exist.
        ValueError: If a channel column is missing, or timestamps are not
            unique, ascending, and a contiguous hourly grid.
    """
    if not path.is_file():
        raise FileNotFoundError(f"Missing joined feature artifact: {path}")
    channel_columns = list(channel_columns)
    frame = pd.read_parquet(path)
    missing = sorted({"timestamp", *channel_columns}.difference(frame.columns))
    if missing:
        raise ValueError(f"Raw channel frame is missing required columns: {missing}")

    timestamps = pd.DatetimeIndex(pd.to_datetime(frame["timestamp"], utc=True))
    if timestamps.has_duplicates or not timestamps.is_monotonic_increasing:
        raise ValueError("Raw channel frame timestamps must be unique and increasing")
    expected_grid = pd.date_range(timestamps[0], periods=len(timestamps), freq="h")
    if not timestamps.equals(expected_grid):
        raise ValueError(
            "Raw channel frame timestamps must be a contiguous hourly grid"
        )
    return frame[channel_columns].set_index(timestamps)


def build_sequences(
    raw_channel_frame: pd.DataFrame,
    candidate_rows: pd.DataFrame,
    *,
    sequence_length: int,
    channel_columns: Sequence[str],
    target_columns: Sequence[str],
    artifact_name: str,
) -> tuple[np.ndarray, np.ndarray, pd.DataFrame]:
    """Build split-local sequence windows for already-eligible issue times.

    ``candidate_rows`` (``dataset.train_rows``/``test_rows``) already satisfy
    ``load_joined_dataset``'s eligibility. This narrows that cohort further: a
    row at timestamp ``t`` is kept only when at least ``sequence_length``
    hours of this split's own raw channel history exist before and including
    ``t`` (never reaching into the other split), and every channel value is
    finite across the whole window. Imputed-but-present hours are fine;
    genuinely missing ones are not.

    Args:
        raw_channel_frame: Timestamp-indexed raw channel frame for this split,
            from :func:`load_raw_channel_frame`.
        candidate_rows: Eligible rows (``dataset.train_rows``/``test_rows``)
            to narrow further by sequence completeness.
        sequence_length: Number of hourly timesteps in each window.
        channel_columns: Ordered raw per-timestep channel columns.
        target_columns: Ordered direct-forecast target columns.
        artifact_name: Human-readable artifact label used in errors.

    Returns:
        A tuple of ``sequences`` (float64, shape ``(n_eligible,
        sequence_length, len(channel_columns))``), ``targets`` (float64,
        shape ``(n_eligible, len(target_columns))``), and ``origins`` (the
        subset of ``candidate_rows`` with a complete window, in chronological
        order with a fresh ``RangeIndex``). ``len(origins) <=
        len(candidate_rows)``.

    Raises:
        ValueError: If ``sequence_length < 1``, a required column is missing,
            or no candidate row has a complete window.
    """
    if sequence_length < 1:
        raise ValueError("sequence_length must be at least 1")
    channel_columns = list(channel_columns)
    target_columns = list(target_columns)
    missing_channels = sorted(
        set(channel_columns).difference(raw_channel_frame.columns)
    )
    if missing_channels:
        raise ValueError(f"Raw channel frame is missing columns: {missing_channels}")
    missing_targets = sorted(set(target_columns).difference(candidate_rows.columns))
    if missing_targets:
        raise ValueError(
            f"Candidate rows are missing target columns: {missing_targets}"
        )

    candidate_timestamps = pd.DatetimeIndex(
        pd.to_datetime(candidate_rows["timestamp"], utc=True)
    )
    positions = raw_channel_frame.index.get_indexer(candidate_timestamps)
    finite_rows = pd.Series(
        np.isfinite(raw_channel_frame[channel_columns].to_numpy(dtype=float)).all(
            axis=1
        ),
        index=raw_channel_frame.index,
    )
    complete_windows = (
        finite_rows.rolling(sequence_length, min_periods=sequence_length)
        .sum()
        .eq(sequence_length)
        .to_numpy()
    )
    safe_positions = np.clip(positions, 0, len(complete_windows) - 1)
    eligible = (positions >= sequence_length - 1) & complete_windows[safe_positions]
    eligible_positions = np.flatnonzero(eligible)
    if not len(eligible_positions):
        raise ValueError(
            f"{artifact_name} has no eligible {sequence_length}-hour sequences"
        )

    channel_values = raw_channel_frame[channel_columns].to_numpy(dtype=float)
    origin_positions = positions[eligible_positions]
    sequences = np.stack(
        [
            channel_values[position - sequence_length + 1 : position + 1]
            for position in origin_positions
        ]
    )
    origins = candidate_rows.iloc[eligible_positions].reset_index(drop=True)
    targets = origins[target_columns].to_numpy(dtype=float)
    return sequences, targets, origins


class _RecurrentForecaster(nn.Module):
    """One-layer-or-more direct multi-horizon GRU or LSTM forecaster."""

    def __init__(
        self,
        *,
        cell_type: str,
        input_size: int,
        hidden_size: int,
        num_layers: int,
        dropout: float,
        forecast_horizon: int,
    ) -> None:
        """Build the recurrent encoder and the multi-horizon linear head."""
        super().__init__()
        recurrent_class = nn.GRU if cell_type == "gru" else nn.LSTM
        self.recurrent = recurrent_class(
            input_size=input_size,
            hidden_size=hidden_size,
            num_layers=num_layers,
            dropout=dropout if num_layers > 1 else 0.0,
            batch_first=True,
        )
        self.head = nn.Linear(hidden_size, forecast_horizon)

    def forward(self, inputs: torch.Tensor) -> torch.Tensor:
        """Predict all forecast horizons from the final recurrent step."""
        outputs, _ = self.recurrent(inputs)
        result: torch.Tensor = self.head(outputs[:, -1, :])
        return result


class RnnForecaster:
    """Thin sklearn-Estimator-shaped wrapper around a torch GRU/LSTM.

    Owns the torch ``nn.Module``, a channel ``StandardScaler`` fit on
    flattened ``(n * L, C)`` training values, a target ``StandardScaler`` fit
    on ``(n, H)`` training targets, and the training loop. The whole fitted
    object round-trips through ``joblib.dump``/``load`` like Ridge's
    ``Pipeline`` or MLP's ``TransformedTargetRegressor``. ``.fit``/``.predict``
    take and return plain numpy arrays, not DataFrames.
    """

    def __init__(
        self,
        *,
        cell_type: str,
        hidden_size: int,
        num_layers: int,
        dropout: float = 0.1,
        learning_rate: float = 0.001,
        max_epochs: int = 50,
        batch_size: int = 64,
        random_state: int = RANDOM_STATE,
        device: str | None = None,
    ) -> None:
        """Store hyperparameters; nothing is fitted until :meth:`fit` runs."""
        if cell_type not in {"gru", "lstm"}:
            raise ValueError(f"cell_type must be 'gru' or 'lstm'; got {cell_type!r}")
        self.cell_type = cell_type
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.dropout = dropout
        self.learning_rate = learning_rate
        self.max_epochs = max_epochs
        self.batch_size = batch_size
        self.random_state = random_state
        self.device = device
        self.module_: _RecurrentForecaster | None = None
        self.channel_scaler_: StandardScaler | None = None
        self.target_scaler_: StandardScaler | None = None
        self.epoch_losses_: list[float] = []

    def fit(self, sequences: np.ndarray, targets: np.ndarray) -> "RnnForecaster":
        """Seed every RNG, fit fresh scalers, train from scratch, move to CPU.

        Args:
            sequences: Training windows, shape ``(n, sequence_length,
                n_channels)``.
            targets: Training targets, shape ``(n, forecast_horizon)``.

        Returns:
            ``self``, with the trained module always moved to CPU so the
            fitted object is joblib-picklable/portable regardless of the
            accelerator used during training.
        """
        random.seed(self.random_state)
        np.random.seed(self.random_state)
        torch.manual_seed(self.random_state)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(self.random_state)

        device = torch.device(self.device or _auto_device())
        n_samples, sequence_length, n_channels = sequences.shape
        forecast_horizon = targets.shape[1]

        self.channel_scaler_ = StandardScaler()
        scaled_channels = self.channel_scaler_.fit_transform(
            sequences.reshape(-1, n_channels)
        ).reshape(n_samples, sequence_length, n_channels)
        self.target_scaler_ = StandardScaler()
        scaled_targets = self.target_scaler_.fit_transform(targets)

        module = _RecurrentForecaster(
            cell_type=self.cell_type,
            input_size=n_channels,
            hidden_size=self.hidden_size,
            num_layers=self.num_layers,
            dropout=self.dropout,
            forecast_horizon=forecast_horizon,
        ).to(device)
        optimizer = torch.optim.Adam(module.parameters(), lr=self.learning_rate)
        loss_function = nn.MSELoss()

        dataset = TensorDataset(
            torch.tensor(scaled_channels, dtype=torch.float32),
            torch.tensor(scaled_targets, dtype=torch.float32),
        )
        loader_generator = torch.Generator().manual_seed(self.random_state)
        loader = DataLoader(
            dataset,
            batch_size=self.batch_size,
            shuffle=True,
            generator=loader_generator,
        )

        epoch_losses: list[float] = []
        for _ in range(self.max_epochs):
            module.train()
            weighted_loss = 0.0
            sample_count = 0
            for batch_sequences, batch_targets in loader:
                batch_sequences = batch_sequences.to(device)
                batch_targets = batch_targets.to(device)
                optimizer.zero_grad()
                loss = loss_function(module(batch_sequences), batch_targets)
                loss.backward()
                optimizer.step()
                weighted_loss += loss.item() * len(batch_sequences)
                sample_count += len(batch_sequences)
            epoch_losses.append(weighted_loss / sample_count)

        self.module_ = module.to("cpu")
        self.epoch_losses_ = epoch_losses
        return self

    def predict(self, sequences: np.ndarray) -> np.ndarray:
        """Scale, run CPU inference, inverse-transform to raw units.

        Args:
            sequences: Windows to score, shape ``(n, sequence_length,
                n_channels)``.

        Returns:
            A finite float64 array, shape ``(len(sequences),
            forecast_horizon)``.

        Raises:
            ValueError: If the estimator has not been fitted.
        """
        if (
            self.module_ is None
            or self.channel_scaler_ is None
            or self.target_scaler_ is None
        ):
            raise ValueError("RnnForecaster must be fitted before predicting")
        n_samples, sequence_length, n_channels = sequences.shape
        scaled_channels = self.channel_scaler_.transform(
            sequences.reshape(-1, n_channels)
        ).reshape(n_samples, sequence_length, n_channels)
        self.module_.eval()
        with torch.no_grad():
            scaled_predictions = self.module_(
                torch.tensor(scaled_channels, dtype=torch.float32)
            ).numpy()
        predictions: np.ndarray = self.target_scaler_.inverse_transform(
            scaled_predictions
        )
        return predictions.astype(np.float64)


def _auto_device() -> str:
    """Return the first available of MPS, CUDA, or CPU."""
    if torch.backends.mps.is_available():
        return "mps"
    if torch.cuda.is_available():
        return "cuda"
    return "cpu"


def build_rnn_estimator(
    *,
    cell_type: str,
    sequence_length: int,
    hidden_size: int,
    num_layers: int,
    dropout: float = 0.1,
    learning_rate: float = 0.001,
    max_epochs: int = 50,
    batch_size: int = 64,
    random_state: int = RANDOM_STATE,
    device: str | None = None,
) -> RnnForecaster:
    """Build one unfitted RnnForecaster.

    The single construction path shared by every CV fold and the final
    retrain, so the saved model never diverges from what was
    cross-validated (same rationale as ``build_ridge_estimator`` /
    ``build_mlp_estimator``).

    Args:
        cell_type: Recurrent cell type, ``"gru"`` or ``"lstm"``.
        sequence_length: Recorded for parity with Ridge/MLP's
            ``build_*_estimator`` convention; not consumed by the module
            (already baked into the sequences passed to ``.fit``/``.predict``).
        hidden_size: Width of the recurrent hidden state.
        num_layers: Number of stacked recurrent layers.
        dropout: Inter-layer dropout (a no-op when ``num_layers == 1``).
        learning_rate: Adam's step size.
        max_epochs: Fixed training-epoch budget.
        batch_size: Minibatch size.
        random_state: Seed for weight initialization and the ``DataLoader``
            shuffle order.
        device: Torch device to train on; ``None`` auto-detects MPS/CUDA/CPU.

    Returns:
        An unfitted :class:`RnnForecaster`.
    """
    del sequence_length
    return RnnForecaster(
        cell_type=cell_type,
        hidden_size=hidden_size,
        num_layers=num_layers,
        dropout=dropout,
        learning_rate=learning_rate,
        max_epochs=max_epochs,
        batch_size=batch_size,
        random_state=random_state,
        device=device,
    )


def select_candidate(
    cv_results: pd.DataFrame, metric: str = "rmse"
) -> tuple[str, int, int, int]:
    """Select one cell_type/sequence_length/hidden_size/num_layers candidate.

    Args:
        cv_results: One row per candidate with mean CV metrics.
        metric: Ranking metric, either ``"mae"`` or ``"rmse"``.

    Returns:
        The winning candidate's ``(cell_type, sequence_length, hidden_size,
        num_layers)``.

    Raises:
        ValueError: If the metric is invalid, results are empty or missing
            required columns, or ranking values contain nulls.
    """
    winner = _select_candidate(cv_results, metric, tie_break_columns=_TIE_BREAK_COLUMNS)
    return (
        str(winner["cell_type"]),
        int(winner["sequence_length"]),
        int(winner["hidden_size"]),
        int(winner["num_layers"]),
    )


def tie_breaking_policy(selection_metric: str) -> list[str]:
    """Describe the candidate tie-breaking order :func:`select_candidate` applies.

    Args:
        selection_metric: Aggregate CV metric used to rank candidates.

    Returns:
        The ordered tie-breaking rules, recorded in the saved manifest.
    """
    return _tie_breaking_policy(selection_metric, _TIE_BREAK_DESCRIPTIONS)


@dataclass(frozen=True)
class RnnManifest:
    """The durable record of one completed RNN execution.

    Attributes:
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        station_id: Target station the model predicts.
        selected_cell_type: Winning recurrent cell type.
        selected_sequence_length: Winning lookback window length, in hours.
        selected_hidden_size: Winning recurrent hidden-state width.
        selected_num_layers: Winning number of stacked recurrent layers.
        fixed_dropout: Fixed inter-layer dropout used by every candidate.
        selection_metric: Aggregate CV metric used to rank candidates.
        channel_columns: Ordered raw per-timestep channels the model reads.
        target_columns: Ordered direct-forecast target columns.
        cv_results: One row per candidate with its CV metrics.
        sealed_test_metrics: Aggregate sealed-test MAE, RMSE, ME, and R².
        horizon_metrics: One sealed-test metric row per forecast horizon.
        scored_test_rows: Sealed-test rows actually scored (``<=
            len(dataset.test_rows)``).
    """

    execution_uuid: str
    station_id: str
    selected_cell_type: str
    selected_sequence_length: int
    selected_hidden_size: int
    selected_num_layers: int
    fixed_dropout: float
    selection_metric: str
    channel_columns: tuple[str, ...]
    target_columns: tuple[str, ...]
    cv_results: pd.DataFrame
    sealed_test_metrics: dict[str, float]
    horizon_metrics: pd.DataFrame
    scored_test_rows: int


def save_rnn_manifest(
    path: Path,
    *,
    model_path: Path,
    execution_uuid: str,
    contract: JoinedFeatureContract,
    channel_columns: Sequence[str],
    selected_cell_type: str,
    selected_sequence_length: int,
    selected_hidden_size: int,
    selected_num_layers: int,
    fixed_dropout: float,
    selection_metric: str,
    cv_results: pd.DataFrame,
    sealed_test_metrics: Mapping[str, float],
    per_horizon_metrics: pd.DataFrame,
    scored_test_rows: int,
    cohort: Mapping[str, object],
    training: Mapping[str, object],
) -> None:
    """Write the manifest that records one completed RNN execution.

    Called once, after the sealed test has been scored, so the manifest never
    describes a run that did not finish.

    Args:
        path: Manifest JSON path to write.
        model_path: Saved RNN joblib model path.
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        contract: Joined-feature contract the model was fitted against.
        channel_columns: Ordered raw per-timestep channels the model reads.
        selected_cell_type: Winning recurrent cell type.
        selected_sequence_length: Winning lookback window length, in hours.
        selected_hidden_size: Winning recurrent hidden-state width.
        selected_num_layers: Winning number of stacked recurrent layers.
        fixed_dropout: Fixed inter-layer dropout used by every candidate.
        selection_metric: Aggregate CV metric used to rank candidates.
        cv_results: One row per candidate with its CV metrics.
        sealed_test_metrics: Aggregate sealed-test MAE, RMSE, ME, and R².
        per_horizon_metrics: Sealed-test metric rows keyed by horizon, as
            returned by :func:`src.metrics.metric_tables`.
        scored_test_rows: Sealed-test rows actually scored.
        cohort: Common-cohort eligibility provenance.
        training: Training-artifact and time-range provenance.

    Raises:
        ValueError: If a sealed-test metric is missing or non-finite, or the
            per-horizon metrics do not cover the forecast contract exactly
            once.
    """
    missing_metrics = sorted(
        set(SEALED_TEST_METRIC_NAMES).difference(sealed_test_metrics)
    )
    if missing_metrics:
        raise ValueError(f"Sealed-test metrics are missing: {missing_metrics}")
    if not all(
        np.isfinite(float(sealed_test_metrics[name]))
        for name in SEALED_TEST_METRIC_NAMES
    ):
        raise ValueError("Sealed-test metrics contain non-finite values")
    horizon_records = _horizon_records(per_horizon_metrics, contract)

    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "model_path": str(model_path),
        "execution_uuid": execution_uuid,
        "model_type": "src.rnn.RnnForecaster",
        "estimator": "nn.GRU/nn.LSTM + nn.Linear head",
        "preprocessor": "StandardScaler (channels), StandardScaler (target)",
        "station_id": contract.station_id,
        "forecast_horizon_hours": len(contract.target_columns),
        "channel_columns": list(channel_columns),
        "target_columns": list(contract.target_columns),
        "selected_cell_type": selected_cell_type,
        "selected_sequence_length": int(selected_sequence_length),
        "selected_hidden_size": int(selected_hidden_size),
        "selected_num_layers": int(selected_num_layers),
        "fixed_dropout": float(fixed_dropout),
        "selection_metric": selection_metric,
        "tie_breaking": tie_breaking_policy(selection_metric),
        "cv_results": _cv_results_records(cv_results),
        "sealed_test_metrics": {
            name: float(sealed_test_metrics[name]) for name in SEALED_TEST_METRIC_NAMES
        },
        "horizon_metrics": horizon_records,
        "scored_test_rows": int(scored_test_rows),
        "common_cohort_eligibility": dict(cohort),
        "training": dict(training),
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def load_rnn_manifest(
    path: Path,
    *,
    contract: JoinedFeatureContract,
    channel_columns: Sequence[str],
) -> RnnManifest:
    """Load an RNN manifest and check it against the current contract.

    Args:
        path: Manifest JSON path to read.
        contract: Current joined-feature contract for the target station.
        channel_columns: Current ``dataset.feature_subsets["raw_all_stations"]``.

    Returns:
        The validated manifest.

    Raises:
        FileNotFoundError: If no manifest exists.
        ValueError: If the manifest was written by another schema version, or
            disagrees with the current contract or channel columns.
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing RNN model manifest: {path}. {MANIFEST_GUIDANCE}"
        )
    manifest = json.loads(path.read_text(encoding="utf-8"))
    schema_version = manifest.get("schema_version")
    if schema_version != MANIFEST_SCHEMA_VERSION:
        raise ValueError(
            f"RNN manifest schema version {schema_version!r} is not "
            f"{MANIFEST_SCHEMA_VERSION!r}. {MANIFEST_GUIDANCE}"
        )
    if manifest.get("station_id") != contract.station_id:
        raise ValueError(
            "RNN manifest station_id does not match the current target station"
        )
    if manifest.get("forecast_horizon_hours") != len(contract.target_columns):
        raise ValueError(
            "RNN manifest forecast horizon does not match the current contract"
        )
    if tuple(manifest.get("target_columns", ())) != contract.target_columns:
        raise ValueError(
            "RNN manifest target contract does not match the current contract"
        )
    if tuple(manifest.get("channel_columns", ())) != tuple(channel_columns):
        raise ValueError(
            "RNN manifest channel columns do not match the current raw_all_stations subset"
        )
    return RnnManifest(
        execution_uuid=str(manifest["execution_uuid"]),
        station_id=str(manifest["station_id"]),
        selected_cell_type=str(manifest["selected_cell_type"]),
        selected_sequence_length=int(manifest["selected_sequence_length"]),
        selected_hidden_size=int(manifest["selected_hidden_size"]),
        selected_num_layers=int(manifest["selected_num_layers"]),
        fixed_dropout=float(manifest["fixed_dropout"]),
        selection_metric=str(manifest["selection_metric"]),
        channel_columns=tuple(manifest["channel_columns"]),
        target_columns=contract.target_columns,
        cv_results=pd.DataFrame(manifest["cv_results"]),
        sealed_test_metrics={
            name: float(manifest["sealed_test_metrics"][name])
            for name in SEALED_TEST_METRIC_NAMES
        },
        horizon_metrics=pd.DataFrame(manifest["horizon_metrics"]),
        scored_test_rows=int(manifest["scored_test_rows"]),
    )


def score_saved_model(
    manifest: RnnManifest,
    model_path: Path,
    test_rows: pd.DataFrame,
    raw_test_channel_frame: pd.DataFrame,
) -> tuple[np.ndarray, pd.DataFrame]:
    """Reload the saved RNN, rebuild sequences, and score the sealed test.

    Args:
        manifest: Validated manifest describing the saved model.
        model_path: Saved RNN joblib model path.
        test_rows: Eligible sealed-test rows (``dataset.test_rows``).
        raw_test_channel_frame: Raw per-timestep test-split channel frame,
            from :func:`load_raw_channel_frame`, used to rebuild lookback
            windows.

    Returns:
        A tuple of ``(predictions, origins)``. The returned row count is NOT
        ``len(test_rows)``: only rows with a complete
        ``manifest.selected_sequence_length``-hour window are scored.
        Downstream metric/plot calls must use ``origins``, not ``test_rows``,
        as their ``actual`` frame.

    Raises:
        ValueError: If the reloaded model's predictions do not match the
            forecast contract.
    """
    sequences, _targets, origins = build_sequences(
        raw_test_channel_frame,
        test_rows,
        sequence_length=manifest.selected_sequence_length,
        channel_columns=manifest.channel_columns,
        target_columns=list(manifest.target_columns),
        artifact_name="saved RNN sealed-test",
    )
    model = load_joblib(model_path)
    predictions = validate_predictions(
        model.predict(sequences),
        expected_rows=len(origins),
        target_columns=list(manifest.target_columns),
        artifact_name="saved RNN sealed-test",
    )
    return predictions, origins


def _cv_results_records(cv_results: pd.DataFrame) -> list[dict[str, object]]:
    """Convert the candidate table to JSON-safe records.

    Args:
        cv_results: One row per candidate with its CV metrics.

    Returns:
        One record per candidate, with plain string, int, and float values.
    """
    int_columns = {
        "sequence_length",
        "hidden_size",
        "num_layers",
        "sequence_eligible_train_rows",
    }
    return [
        {
            str(key): (
                str(value)
                if key == "cell_type"
                else int(value)
                if key in int_columns
                else float(value)
            )
            for key, value in record.items()
        }
        for record in cv_results.to_dict(orient="records")
    ]


def _horizon_records(
    per_horizon_metrics: pd.DataFrame,
    contract: JoinedFeatureContract,
) -> list[dict[str, object]]:
    """Convert per-horizon sealed-test metrics to JSON-safe records.

    Args:
        per_horizon_metrics: Sealed-test metric rows keyed by horizon.
        contract: Joined-feature contract defining the expected horizons.

    Returns:
        One ``test_``-prefixed metric record per forecast horizon, in order.

    Raises:
        ValueError: If the horizons do not cover the forecast contract exactly
            once, or a metric is missing or non-finite.
    """
    expected_horizons = list(range(1, len(contract.target_columns) + 1))
    missing_columns = sorted(
        {"horizon_hours", "mae", "rmse", "me", "r2"}.difference(
            per_horizon_metrics.columns
        )
    )
    if missing_columns:
        raise ValueError(
            f"Sealed-test horizon metrics are missing columns: {missing_columns}"
        )
    if per_horizon_metrics["horizon_hours"].tolist() != expected_horizons:
        raise ValueError(
            "Sealed-test horizon metrics do not match the forecast contract"
        )
    records: list[dict[str, object]] = []
    for horizon, row in zip(
        expected_horizons, per_horizon_metrics.itertuples(), strict=True
    ):
        values = {
            f"test_{metric}": float(getattr(row, metric))
            for metric in ("mae", "rmse", "me", "r2")
        }
        if not all(np.isfinite(value) for value in values.values()):
            raise ValueError("Sealed-test horizon metrics contain non-finite values")
        records.append({"horizon_hours": horizon, **values})
    return records
