"""XGBoost candidate selection, construction, and model manifest helpers."""

import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from joblib import load as load_joblib  # type: ignore[import-untyped]
from xgboost import XGBRegressor  # type: ignore[import-untyped]

from src.config import RANDOM_STATE
from src.dataset import JoinedFeatureContract
from src.model_selection import select_candidate as _select_candidate
from src.model_selection import tie_breaking_policy as _tie_breaking_policy
from src.training import numeric_predictors, validate_predictions

# Manifest layout written by this module. There is no back-compatible reader:
# a manifest from an older schema must be regenerated by re-running the notebook.
MANIFEST_SCHEMA_VERSION = "3.0"
MANIFEST_GUIDANCE = (
    "Run 04_04_train_xgboost.ipynb through its sealed-test cell to write one."
)

_TIE_BREAK_COLUMNS = [
    "feature_count",
    "max_depth",
    "n_estimators",
    "learning_rate",
    "subsample",
    "colsample_bytree",
    "reg_lambda",
    "subset",
]
_TIE_BREAK_DESCRIPTIONS = [
    "fewer features",
    "smaller max_depth",
    "fewer n_estimators",
    "smaller learning_rate",
    "smaller subsample",
    "smaller colsample_bytree",
    "smaller reg_lambda",
    "stable subset name",
]


def select_candidate(
    cv_results: pd.DataFrame, metric: str = "rmse"
) -> tuple[str, int, int, float, float, float, float]:
    """Select one subset/hyperparameter candidate with deterministic tie-breaking.

    Args:
        cv_results: One row per candidate subset/hyperparameter combination
            with mean CV metrics.
        metric: Ranking metric, either ``"mae"`` or ``"rmse"``.

    Returns:
        The winning candidate's subset name, max_depth, n_estimators,
        learning_rate, subsample, colsample_bytree, and reg_lambda.

    Raises:
        ValueError: If the metric is invalid, results are empty or missing
            required columns, or ranking values contain nulls.
    """
    winner = _select_candidate(cv_results, metric, tie_break_columns=_TIE_BREAK_COLUMNS)
    return (
        str(winner["subset"]),
        int(winner["max_depth"]),
        int(winner["n_estimators"]),
        float(winner["learning_rate"]),
        float(winner["subsample"]),
        float(winner["colsample_bytree"]),
        float(winner["reg_lambda"]),
    )


def tie_breaking_policy(selection_metric: str) -> list[str]:
    """Describe the candidate tie-breaking order :func:`select_candidate` applies.

    Args:
        selection_metric: Aggregate CV metric used to rank candidates.

    Returns:
        The ordered tie-breaking rules.
    """
    return _tie_breaking_policy(selection_metric, _TIE_BREAK_DESCRIPTIONS)


def build_xgboost_estimator(
    *,
    max_depth: int,
    learning_rate: float,
    n_estimators: int,
    subsample: float,
    colsample_bytree: float,
    reg_lambda: float,
    n_jobs: int = -1,
    random_state: int = RANDOM_STATE,
) -> XGBRegressor:
    """Build one multi-output XGBoost estimator.

    The single construction path shared by the CV fold loop and the final
    retrain, so the saved model never diverges from what was cross-validated.
    Trees are invariant to monotonic feature transforms and need no predictor
    scaling, so unlike Ridge/MLP no preprocessing pipeline wraps the estimator,
    and there is no feature-columns argument to name a preprocessing step for.

    Args:
        max_depth: Maximum tree depth.
        learning_rate: Boosting step-size shrinkage.
        n_estimators: Number of boosted trees per output.
        subsample: Row subsampling ratio per boosting round.
        colsample_bytree: Column subsampling ratio per tree.
        reg_lambda: L2 regularization strength on leaf weights.
        n_jobs: Number of parallel threads used by the estimator.
        random_state: Seed for row/column subsampling reproducibility.

    Returns:
        An ``XGBRegressor`` fitting one tree per target column via
        ``multi_strategy="one_output_per_tree"``.
    """
    return XGBRegressor(
        max_depth=max_depth,
        learning_rate=learning_rate,
        n_estimators=n_estimators,
        subsample=subsample,
        colsample_bytree=colsample_bytree,
        reg_lambda=reg_lambda,
        tree_method="hist",
        multi_strategy="one_output_per_tree",
        n_jobs=n_jobs,
        random_state=random_state,
    )


@dataclass(frozen=True)
class XgboostManifest:
    """The durable record of one completed XGBoost execution.

    Attributes:
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        station_id: Target station the model predicts.
        selected_subset: Name of the winning ablation subset.
        selected_max_depth: Winning maximum tree depth.
        selected_n_estimators: Winning number of boosted trees per output.
        selected_learning_rate: Winning boosting step-size shrinkage.
        selected_subsample: Winning row subsampling ratio.
        selected_colsample_bytree: Winning column subsampling ratio.
        selected_reg_lambda: Winning L2 regularization strength.
        selected_feature_columns: Ordered predictors the model was fitted on.
        target_columns: Ordered direct-forecast target columns.
    """

    execution_uuid: str
    station_id: str
    selected_subset: str
    selected_max_depth: int
    selected_n_estimators: int
    selected_learning_rate: float
    selected_subsample: float
    selected_colsample_bytree: float
    selected_reg_lambda: float
    selected_feature_columns: tuple[str, ...]
    target_columns: tuple[str, ...]


def save_xgboost_manifest(
    path: Path,
    *,
    model_path: Path,
    execution_uuid: str,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
    selected_subset: str,
    selected_max_depth: int,
    selected_n_estimators: int,
    selected_learning_rate: float,
    selected_subsample: float,
    selected_colsample_bytree: float,
    selected_reg_lambda: float,
) -> None:
    """Write the model-only manifest for one fitted XGBoost estimator.

    Args:
        path: Manifest JSON path to write.
        model_path: Saved XGBoost joblib model path.
        execution_uuid: UUID tying the manifest to its MLflow run hierarchy.
        contract: Joined-feature contract the model was fitted against.
        feature_subsets: The named ablation subsets, in contract order.
        selected_subset: Name of the winning ablation subset.
        selected_max_depth: Winning maximum tree depth.
        selected_n_estimators: Winning number of boosted trees per output.
        selected_learning_rate: Winning boosting step-size shrinkage.
        selected_subsample: Winning row subsampling ratio.
        selected_colsample_bytree: Winning column subsampling ratio.
        selected_reg_lambda: Winning L2 regularization strength.

    Raises:
        ValueError: If the selected subset is unknown.
    """
    if selected_subset not in feature_subsets:
        raise ValueError(f"Selected subset {selected_subset!r} is not a known subset")
    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "model_path": str(model_path),
        "execution_uuid": execution_uuid,
        "model_type": "xgboost.XGBRegressor",
        "estimator": "XGBRegressor",
        "preprocessor": "None (tree-based, no scaling)",
        "station_id": contract.station_id,
        "forecast_horizon_hours": len(contract.target_columns),
        "selected_subset": selected_subset,
        "selected_feature_columns": list(feature_subsets[selected_subset]),
        "target_columns": list(contract.target_columns),
        "selected_max_depth": int(selected_max_depth),
        "selected_n_estimators": int(selected_n_estimators),
        "selected_learning_rate": float(selected_learning_rate),
        "selected_subsample": float(selected_subsample),
        "selected_colsample_bytree": float(selected_colsample_bytree),
        "selected_reg_lambda": float(selected_reg_lambda),
    }
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def load_xgboost_manifest(
    path: Path,
    *,
    contract: JoinedFeatureContract,
    feature_subsets: Mapping[str, Sequence[str]],
) -> XgboostManifest:
    """Load an XGBoost manifest and check it against the current contract.

    Args:
        path: Manifest JSON path to read.
        contract: Current joined-feature contract for the target station.
        feature_subsets: Named feature subsets built from ``contract``.

    Returns:
        The validated manifest.

    Raises:
        FileNotFoundError: If no manifest exists.
        ValueError: If the manifest was written by another schema version, or
            disagrees with the current contract or subset definitions.
    """
    if not path.is_file():
        raise FileNotFoundError(
            f"Missing XGBoost model manifest: {path}. {MANIFEST_GUIDANCE}"
        )
    manifest = json.loads(path.read_text(encoding="utf-8"))
    schema_version = manifest.get("schema_version")
    if schema_version != MANIFEST_SCHEMA_VERSION:
        raise ValueError(
            f"XGBoost manifest schema version {schema_version!r} is not "
            f"{MANIFEST_SCHEMA_VERSION!r}. {MANIFEST_GUIDANCE}"
        )
    if manifest.get("station_id") != contract.station_id:
        raise ValueError(
            "XGBoost manifest station_id does not match the current target station"
        )
    if manifest.get("forecast_horizon_hours") != len(contract.target_columns):
        raise ValueError(
            "XGBoost manifest forecast horizon does not match the current contract"
        )
    if tuple(manifest.get("target_columns", ())) != contract.target_columns:
        raise ValueError(
            "XGBoost manifest target contract does not match the current contract"
        )
    selected_subset = manifest.get("selected_subset")
    if selected_subset not in feature_subsets:
        raise ValueError(
            f"XGBoost manifest selected subset {selected_subset!r} is not a subset "
            "of the current contract"
        )
    selected_feature_columns = tuple(manifest.get("selected_feature_columns", ()))
    if selected_feature_columns != tuple(feature_subsets[selected_subset]):
        raise ValueError(
            "XGBoost manifest selected features do not match the selected subset "
            "contract"
        )
    return XgboostManifest(
        execution_uuid=str(manifest["execution_uuid"]),
        station_id=str(manifest["station_id"]),
        selected_subset=str(selected_subset),
        selected_max_depth=int(manifest["selected_max_depth"]),
        selected_n_estimators=int(manifest["selected_n_estimators"]),
        selected_learning_rate=float(manifest["selected_learning_rate"]),
        selected_subsample=float(manifest["selected_subsample"]),
        selected_colsample_bytree=float(manifest["selected_colsample_bytree"]),
        selected_reg_lambda=float(manifest["selected_reg_lambda"]),
        selected_feature_columns=selected_feature_columns,
        target_columns=contract.target_columns,
    )


def score_saved_model(
    manifest: XgboostManifest,
    model_path: Path,
    test_rows: pd.DataFrame,
) -> np.ndarray:
    """Reload the saved XGBoost model and score the sealed-test cohort.

    Args:
        manifest: Validated manifest describing the saved model.
        model_path: Saved XGBoost joblib model path.
        test_rows: Eligible sealed-test rows to score.

    Returns:
        Validated sealed-test predictions ordered like the manifest's targets.

    Raises:
        ValueError: If the reloaded model's predictions do not match the
            forecast contract.
    """
    model = load_joblib(model_path)
    return validate_predictions(
        model.predict(numeric_predictors(test_rows, manifest.selected_feature_columns)),
        expected_rows=len(test_rows),
        target_columns=list(manifest.target_columns),
        artifact_name="saved XGBoost sealed-test",
    )
